### ISSUE TITLE
"Blue Iris NVR" not in Home Assistant Community Add-ons

### ISSUE THREAD

**Issue by yang3535** [elad-bar/ha-blueiris#101]
I can't find "Blue Iris NVR" under Supervisor>Add-on Store>Home Assistant Community Add-ons.  Is that where it's supposed to be or do I need to ad a custom repository?

**Comment by Dave-Casey** [comment]
Did you install using HACS first?

**Comment by elad-bar** [comment]
Addon store is for addons, BI integration is a custom component 

You should install HACS as custom component, restart, go to HACS and install BlueIris, restart again and then you will have it

**Comment by yang3535** [comment]
Thanks for responding.  I didn't realize that Home Assistant Community Add-Ons wasn't HACS.

**Comment by elad-bar** [comment]
pls let me know once you've manage to make it work, leaving the issue still open

**Comment by yang3535** [comment]
I've successfully installed HACS and found the Blue Iris NVR repository and installed it.  I'm still anxiously waiting for components to put together Blue Iris, so I won't know how things work until I get my BI instance up and running.

Thanks for your help.

**Comment by elad-bar** [comment]
Np
