### ISSUE TITLE
Setup failed for blueiris

### ISSUE THREAD

**Issue by Darnshelm** [elad-bar/ha-blueiris#102]
Hi
I restared my HA after that I get this messeger on blueiris and I cant see any cameras any more

Setup failed for blueiris: Unable to import component: cannot import name 'CONF_PAYLOAD_AVAILABLE' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)

**Comment by OliPassey** [comment]
I have this after latest HA update also.
Exact same error.

**Comment by elad-bar** [comment]
are you on the latest version (1.0.2)? 
asking because the latest version doesn't contain that import

thanks

**Comment by OliPassey** [comment]
Ah yes, i keep missing updates in HACS. 
Thanks for your help on this - its greatly appreciated.

**Comment by kramttocs** [comment]
Closing per comments that this was fixed via 1.0.2
