### ISSUE TITLE
json, Error

### ISSUE THREAD

**Issue by meden199** [elad-bar/ha-blueiris#103]
Sinds a couple of days my camera's are not visible in HomeAssistant.
In the log i see:  Failed to connect http://192.168.*.*:81/json, Error: Cannot connect to host 192.168.1.*.*::81 ssl:False [Connect call failed ('192.168.1.*.*: 81)], Line: 84

When I go with a browser to 192.168.1.*.*::81 everything works perfect.

**Comment by elad-bar** [comment]
it means you have timeouts from time to time, do you have server monitoring to check whether at the time there are error what is the CPU usage?

**Comment by meden199** [comment]
After a update of the core the problem was solved.

Now after a environment power fail the problee is Back.
I'm running HA in a VMware Workstation Pro and BueIris on the VMware host.

**Comment by meden199** [comment]
After a core update the problem was solved.
