### ISSUE TITLE
A "grouped" binary_sensor for motion?

### ISSUE THREAD

**Issue by Kedryn** [elad-bar/ha-blueiris#116]
Maybe can be useful to have an additional general motion sensor that groups any single motion sensor (DIO, External and Motion).
For example, before switching to BI Integration, i had a rest api that triggers the motion sensor of the BI camto have it, in turn, ask to HA to turn on the lights.
Now i had to add many other sensor to my automation because my api call triggers the "external" motion sensor, that wasn't included in the triggers of that automation. This for all my 11 cameras.

**Comment by kramttocs** [comment]
Sorry, I don't know that I understand. Can you provide more details? HA allows you to group entities pretty easily now - will that do what you need?

**Comment by Kedryn** [comment]
> Sorry, I don't know that I understand. Can you provide more details? HA allows you to group entities pretty easily now - will that do what you need?

Not completely. 
For example, i had cameras and sensor that, via MQTT, are sending "on" to many binary_sensor device_class motion.
They worked flawless until feb.
I had to rewrite the code using "middle level" groups and template binary sensors to keep having same binary_sensor names without rewriting the rest of the yaml code, all to have "on" and "off" only, without the third binary_state of uknown.
It would be easy, HA side, to include the initial_state property even for mqtt binary_sensors, so i could simpy had a "intial_state: off" to keep code compatibility at 100%.

anyway, i rewrote the code.

**Comment by kramttocs** [comment]
Again, I apologize but I am not understanding what you are asking the BI integration to do.

**Comment by Kedryn** [comment]
Sorry, but last message wasn't for this thread, but for HA forums. I don't really understand how i posted that here, and i'll delete it because it's offtopic here.

Anyway, what i was asking for is for one more sensor in this integration, that goes on if any of the 3 (dio, motion and external) goes on.
I know (and i'm doing that) that can use groups in HA, but i have like 20 cameras, and making groups by hand means that i have to modify them every time i change something in cam naming. 
Having that binary_sensor already in the integration, would make easier for us to manage motion sensors.

**Comment by kramttocs** [comment]
Thanks and I appreciate the idea but I think grouping them in HA is the appropriate solution for this. I feel that having the individual sensors are the best approach and the end user can work with those as needed.
