### ISSUE TITLE
Audio Binary Sensor Issue

### ISSUE THREAD

**Issue by dbs179** [elad-bar/ha-blueiris#117]
I've gone through the process of setting up all of the MQTT settings in HA and Blue Iris.  My settings are a bit different as I'm using Deep Stack (AI) for object detection, so I had to set the option "Fire non-email/SMS/Push actions regardless" setting under Camera Settings > Trigger > Artificial Intelligence.  

When I set this, my Motion Detection works fine, i.e. shows motion detected when motion is in the picture and shows clear after the , but the Audio Sensor does not turn on until the Audio trigger stops, shows detection for less than a second and then shows clear.

I've validated all of the MQTT messages using MQTT Explorer and that is the behavior I get, so it looks like perhaps a Blue Iris issue, but wanted to see if I might be missing something.

**Comment by kramttocs** [comment]
So Blue Iris is sending the Audio message after the trigger stops and not as soon as it is initiated?

**Comment by kramttocs** [comment]
Please report this to Ken at BI. Thanks
