### ISSUE TITLE
watchdog inversion not working correctly

### ISSUE THREAD

**Issue by Hisma** [elad-bar/ha-blueiris#12]
In your code in binary_sensor.py, it shows that a WATCHDOG connectivity sensor is inverted... that is, OFF = connected, ON = disconnected.  
However, in my system, the inversion code does not work correctly, because my system still showed OFF as disconnected, so my watchdog sensor reports disconnected when the camera is working fine.  
I had to create a binary template to invert the sensor and I'm using that instead of the original.  
Is there any reason why the watchdog sensor would not work correctly for me while it works fine for others?

**Comment by darkgrue** [comment]
The inversion works, the problem is that the connectivity state is undetermined when the system starts, because no MQTT messages have been received (all sensors appear to start in the `off` state).

Inverting the sensor is the incorrect solution. You need to set the sensor to have an initial state of  `on`. I'll address this in a future Pull Request.

**Comment by Hisma** [comment]
Got it, this makes sense.  Since updating to BI5, watchdog state is no longer an option from the alerts menu, so no way to get status via MQTT.  Don't know if they did that deliberately or not.  I'm just going to remove watchdog status from HA until it's fixed.

**Comment by darkgrue** [comment]
> Got it, this makes sense. Since updating to BI5, watchdog state is no longer an option from the alerts menu, so no way to get status via MQTT. Don't know if they did that deliberately or not. I'm just going to remove watchdog status from HA until it's fixed.

It's been removed from the Alerts tab, but it's still on the Watchdog tab (which _used_ to redirect to the Alerts tab in BI4 - looks like it's distinct now). Look for the "On loss of signal..." and "On signal restoration..." buttons to set the Action Set (which can include a MQTT message) for each condition.

On the downside, a number of features appear to be broken or unreliable in BI5 yet, so hold on to your hats for a bit...
