### ISSUE TITLE
Update to 1.0.6 failed on 2021.7.4

### ISSUE THREAD

**Issue by sotatech** [elad-bar/ha-blueiris#121]
I just updated to 1.0.6 and I'm getting Invalid Config:The following integrations and platforms could not be set up:
blueiris.binary_sensor

From the logs:
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 9:23:57 (2 occurrences)
Last logged: 9:27:04

Unable to prepare setup for platform blueiris.binary_sensor: Platform not found (cannot import name 'ReceiveMessage' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)).

**Comment by elad-bar** [comment]
Please install v1.0.5, v1.0.6 is for HA 2021.8 and above

**Comment by sotatech** [comment]
1.0.6 was offered as an update in HACS, so I installed it. I have tried it on my 2021.8 beta test system and it works fine, so I'll wait for it to be released. You might want to consider a warning on HACS to avoid others making the same mistake.

**Comment by Dave-Casey** [comment]
@sotatech did you find a way to roll back to the previous version in HACS?

**Comment by sotatech** [comment]
Yes, HACS offered an "upgrade" back to 1.0.5. I installed it and that rolled the Blue Iris integration back. It's been working fine since.

**Comment by dadz01** [comment]
Hey i rolled back to 1.0.5 but now the integration doesn't show up as an integration in the integration tab at all
