### ISSUE TITLE
V1.06 Fails on Start Up

### ISSUE THREAD

**Issue by johnjoemorgan** [elad-bar/ha-blueiris#122]
This error originated from a custom integration.

Logger: custom_components.blueiris.managers.entity_manager
Source: custom_components/blueiris/managers/entity_manager.py:577
Integration: Blue Iris NVR (documentation)
First occurred: 18:47:18 (4 occurrences)
Last logged: 18:48:38

Failed to update, step: Start updating domain binary_sensor, Error: 'binary_sensor', Line: 197

**Comment by elad-bar** [comment]
Please install v1.0.5, v1.0.6 is for HA 2021.8 and above

**Comment by elad-bar** [comment]
Dup #121
