### ISSUE TITLE
Startup Failure on 2021.8.0

### ISSUE THREAD

**Issue by sockmonkey0223** [elad-bar/ha-blueiris#123]
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 9:02:04 AM (1 occurrences)
Last logged: 9:02:04 AM

Unable to prepare setup for platform blueiris.binary_sensor: Platform not found (cannot import name 'Message' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)).

---

This error originated from a custom integration.

Logger: custom_components.blueiris.managers.entity_manager
Source: custom_components/blueiris/managers/entity_manager.py:577
Integration: Blue Iris NVR (documentation)
First occurred: 9:02:05 AM (16 occurrences)
Last logged: 9:09:34 AM

Failed to update, step: Start updating domain binary_sensor, Error: 'binary_sensor', Line: 197

**Comment by elad-bar** [comment]
Fixed in v1.0.6
