### ISSUE TITLE
failed to update binary sensor

### ISSUE THREAD

**Issue by BigRed8150** [elad-bar/ha-blueiris#124]
I got this when i updated to 1.0.6

This error originated from a custom integration.

Logger: custom_components.blueiris.managers.entity_manager
Source: custom_components/blueiris/managers/entity_manager.py:577
Integration: Blue Iris NVR (documentation)
First occurred: 8:45:34 PM (7 occurrences)
Last logged: 8:48:32 PM

Failed to update, step: Start updating domain binary_sensor, Error: 'binary_sensor', Line: 197

**Comment by rwperkinsjr** [comment]
I get the same error and had to revert to 1.0.5 to get it to work.

**Comment by JOHLC** [comment]
Are you on Home Assistant version 2021.8.0? If not, that may be why it broke for you considering the title of this latest BI component release is: "Support MQTT for 2021.8.0 and above"

**Comment by rwperkinsjr** [comment]
> Are you on Home Assistant version 2021.8.0? If not, that may be why it broke for you considering the title of this latest BI component release is: "Support MQTT for 2021.8.0 and above"

Yep, that was my issue. i thought I had updated to 2021.8.0 but I didn't realize the update failed. Once I got the update for HA in 1.0.6 went right in with zero issues.

Thank you for reminding me check myself.

**Comment by tmoran3020** [comment]
I updated main HA this morning, got the breaking change - same error as above, upgraded the blueiris plugin, works great.

@BigRed8150 go into HACS, it will tell you that blueiris needs to be upgraded. Click the button, restart HA, all is well.
