### ISSUE TITLE
Is it dead ? Blue Iris integration with Home Assistant

### ISSUE THREAD

**Issue by waynerigley** [elad-bar/ha-blueiris#125]
After a few updates im no longer able to see any links from Blue Iris in Home Assistant. I also lost another item that I had to add into my Config.yaml to allow rev proxies and that's all good now. I can link from outside still from a domain to my :85 screen no issues but Home Assistant is still a No Go. Has anyone also dealing with this issue ? is there a Fix or workaround ? 
![camera](https://user-images.githubusercontent.com/44474035/128288777-46f8702f-f5a5-4c77-b376-5920af1c1c74.png)

**Comment by tmoran3020** [comment]
You probably upgraded HA, there was a breaking change. I went into HACS, upgraded the blueiris integration, restarted and boom everything works again.

**Comment by tmoran3020** [comment]
(BTW, thanks for the proactive fix @elad-bar. Thought I was going to need to address in a PR since this integration is theoretically "not supported" but nope, the updated version was already available and works great.)

**Comment by floodwayprintco** [comment]
Just chiming in before this closes to say that yes, I too had the same issue and it was pretty much the same solution. Except I had updated BlueIrisNVR before updating HomeAssistant. So just confirming that when both are updated I am fully back online. Now to set up some alerts so I can detect it next time!

**Comment by goldbondxyz** [comment]
I had zero issue 1.0.5. I upgraded to 1.0.6 and now BI connectivity is dead. I have this popping up in logs:
_**Invalid config
The following integrations and platforms could not be set up:

blueiris.binary_sensor
Please check your config and logs.**_

If I rollback to 1.0.5, it works fine again. I am on the latest HA.

**Comment by floodwayprintco** [comment]
@goldbondxyz have you tried reconfiguring the BlueIrising integration? Maybe need to 'rebuild config files' or whatever the setting is.

**Comment by don86nl** [comment]
> (BTW, thanks for the proactive fix @elad-bar. Thought I was going to need to address in a PR since this integration is theoretically "not supported" but nope, the updated version was already available and works great.)

Same here! Thanks again for the update, elad-bar

**Comment by goldbondxyz** [comment]
> @goldbondxyz have you tried reconfiguring the BlueIrising integration? Maybe need to 'rebuild config files' or whatever the setting is.

I managed to get BI integration installed no issue awhile ago. But, not sure what you are talking about re. rebuild config files.

**Comment by waynerigley** [comment]
Well, Blue Iris is running with no issues, HA is fully up to date ( Ver core-2021.8.2 & Operating Ver 5.10.53 ) but still no Blue Iris image THEN after reading a few of your comments I totally forgot about HACS so I went there and well there was an update to the Blue Iris ! Went ahead and completed the update and BOOM all working again! Thanks all for the help!

**Comment by elad-bar** [comment]
Are you on the latest HA BI component version (1.0.6)?

**Comment by asemev** [comment]
Hi all, i'm also having very strange behavior:

- HACS installation v1.0.7 done
- Integrations: i could find and install it. but then it stopped working after a while.
- i deleted the integation and try to install it again but i cannot find blueiris in the list. 
- I tried removing the HACS component and re-installing and restarting HA but still cannot find blue iris anymore in thje integrations. so weird.
- i'm running HAOS 7.0 and HA core 2021.12.4.

Any ideas?

**Comment by goldbondxyz** [comment]
> Hi all, i'm also having very strange behavior:
> 
> * HACS installation v1.0.7 done
> * Integrations: i could find and install it. but then it stopped working after a while.
> * i deleted the integation and try to install it again but i cannot find blueiris in the list.
> * I tried removing the HACS component and re-installing and restarting HA but still cannot find blue iris anymore in thje integrations. so weird.
> * i'm running HAOS 7.0 and HA core 2021.12.4.
> 
> Any ideas?

Is UI3 working okay with Blue Iris directly? I ran a new an issue after all the upgrades on everything because of log 4J I think. I could not get UI3 or hacks to work properly to show cameras. I ended up re-importing my most recent settings into Blue Iris which resulted in having a reactivate for some weird reason and I was back to normal. I don't know if this was a symptom of cause or what. But both were not working about a week and a half ago

**Comment by asemev** [comment]
Yes UI3 works well directly. i managed to fix my problem by shutting down HA completely and powering off and then on. i noticed this strange behaviour with other HA addons. I think in some cases the docker containers become zombied and the only way to kill them is to turn the power off. just restarting/rebooting HA doesnt help.

**Comment by elad-bar** [comment]
Hi, is that issue related to the component? 
Thanks

**Comment by kramttocs** [comment]
Closing as it sounds like this behavior was fixed in 1.0.6. @waynerigley if you are still having an issue, let us know. Thank you
