### ISSUE TITLE
The camera entity does not support requesting width and height

### ISSUE THREAD

**Issue by djryan012** [elad-bar/ha-blueiris#127]
I know you have stepped away from this project. But HA is now giving this Warning in my logs for most of my camera's and not sure what I can do from my setup

"The camera entity camera.blueiris_front_door does not support requesting width and height, please open an issue with the integration author"

**Comment by rhoddan** [comment]
Same here

**Comment by douglasfl** [comment]
Same error!

**Comment by kramttocs** [comment]
I've submitted a pull request that should resolve this
https://github.com/elad-bar/ha-blueiris/pull/141

**Comment by kramttocs** [comment]
Fixed in v1.0.8. Can someone confirm? Thanks

**Comment by djryan012** [comment]
Have updated to 1.0.9 and no longer flags as an error in Home Assistant.
