### ISSUE TITLE
Can't find "Blue Iris NVR" in the list of integration

### ISSUE THREAD

**Issue by zuohaot** [elad-bar/ha-blueiris#129]
Blue Iris NVR integration: I've tried both 1.0.5 and 1.0.6
HA ver.: 2021.10.7
HA core: 6.6

I am trying to set up my Blue Iris on HA. However, I can't find the integration in the list after I successfully installed it via HACS. I have tried reboot, reinstall, uninstall then install. None of them helped. I wonder if I missed something or it's a bug. Thanks

**Comment by asemev** [comment]
Hi, i have the same problem. did you figure out the solution?

**Comment by elad-bar** [comment]
After installing the component,  if there are no issues,
please try to restart HA, if you still cannot find, clean browser cache.
