### ISSUE TITLE
Invalid server details - UI3 is working

### ISSUE THREAD

**Issue by tonjenny** [elad-bar/ha-blueiris#136]
Hello elad-bar,

I have been trying to setup Blue Iris NVR but it fails.
I can access to cameras with ui3 though.

Could you pls help me out, I am quite noob in network stuffs.

below are error logs,

Cannot complete login
4:35:04 PM – (WARNING) Blue Iris NVR (custom integration)
Failed to access BlueIris Server (192.168.0.114)
4:35:04 PM – (WARNING) Blue Iris NVR (custom integration)
Failed to connect http://192.168.0.114:81/json, Error: Cannot connect to host 192.168.0.114:81 ssl:False [Connect call failed ('192.168.0.114', 81)], Line: 84
4:35:04 PM – (ERROR) Blue Iris NVR (custom integration)

Thanks,

edit : Tried to change ui3 timeout to "none" as your suggestion in another topic but not work.

**Comment by kramttocs** [comment]
Is BI running on port 81?
Where is HA running from?
Can you verify it has access to hit the BI url?

**Comment by iceman73** [comment]
I am having this same issue, seems something changed in the newer HA Versions

**Comment by kramttocs** [comment]
Odd. Mine is still working fine and I actually just removed and re-added the integration back this weekend as I was changing ports around.

**Comment by iceman73** [comment]
I reloaded the latest version, and now its working properly on my installation

**Comment by kramttocs** [comment]
@tonjenny Are you still having this issue?

**Comment by the0ckid82** [comment]
I am also having this issue as well

**Comment by kramttocs** [comment]
This is generally a config issue with either the network or the BI settings. Can you provide more details on what is happening as well as the logs? Thanks

**Comment by kramttocs** [comment]
Any luck in getting me some details for this?

**Comment by kramttocs** [comment]
Please reopen a new issue with details if this is still occurring.
