### ISSUE TITLE
Error in log: Unable to find service logger.set_level

### ISSUE THREAD

**Issue by magyartj** [elad-bar/ha-blueiris#137]
Running Home Assistant 2021.12.6
Blue Iris 5.4.5.5 (1/20/2022)

I've had the BlueIris integraton running for about a week now and it was working great. However the last successful trigger of motion on my security cameras was January 27 at 7:33:36pm. Last night I tried to turn on the logging. to the Debug level in the dropdown. I then rebooted HA. In the logs (Configuration->Settings->Logs I see this error message now shortly after the reboot:

```
This error originated from a custom integration.

Logger: custom_components.blueiris
Source: custom_components/blueiris/__init__.py:40
Integration: Blue Iris NVR (documentation)
First occurred: January 28, 2022, 11:58:13 PM (1 occurrences)
Last logged: January 28, 2022, 11:58:13 PM

Failed to load BlueIris, error: Unable to find service logger.set_level, line: 27

```

In the Integrations list it shows up like this:

![image](https://user-images.githubusercontent.com/97311194/151675449-26351bdc-5177-4334-badc-015a04fc3697.png)

I wanted to change the log level back but when I go into Integrations->Blue Iris->Configure it won't let me and display an error dialog: 

"Error: Config flow could not be loaded"

Seems like I'm stuck!

If I have MQTT Settings (Integrations->MQTT Broker->Configure) in HA listen to a topic, and then trigger an alert in BI, it does get the message

Message 1 received on BlueIris/BarnCamWest/Status at 2:51 PM:
{
    "type": "MOTION_A",
    "trigger": "ON"
}

But the HA BlueIris for whatever reason doesn't pick it up, since Jan 27th. 

Any ideas what is happening, or what this logger.set_level issue is?

Thanks,

**Comment by kramttocs** [comment]
The cause for the logger.set_level error is that it Logging isn't turned on in HA so that service doesn't exist.
In your configuration.yaml add this:

logger:
  default: warning

Save and restart. You can set the default to another level if you'd like.
Do note that if you change the log level via the Blue Iris options back to Default (say you had it at info to view more detail but are done with it now) you will need to restart HA.

**Comment by kramttocs** [comment]
Please see comment above. If you still have issues, let us know and we can reopen.
