### ISSUE TITLE
MQTT topics for motion detection do not match

### ISSUE THREAD

**Issue by mjoshd** [elad-bar/ha-blueiris#14]
Note: I am using Blue Iris 5.. perhaps the behavior has changed since v4.

When using the topic ```BlueIris/&CAM/&TYPE``` for both the trigger and trigger-reset alerts, messages are actually being sent to two different topics.

e.g.
the trigger sends ```MOTION_A = ON```

the the trigger-reset sends ```MOTION = OFF```

This results in the binary motion sensor being set to 'on' in Home Assistant but it was never being set to 'off' since that message was coming in on a different topic.

I was able to work around this by setting the trigger-reset topic to ```BlueIris/&CAM/MOTION_A```

Is this behavior with different topics expected and or different from how it behaved in Blue Iris v4?

Am I not supposed to use the same topic for both alerts? This is how I understood it from the instructions. 

Is the custom component supposed to compensate for the topics being different?

**Comment by brafster** [comment]
Picked up the same issue. Thanks for the workaround for now!

**Comment by marrobHD** [comment]
Hope he will fix it

**Comment by elad-bar** [comment]
the issue is related to BlueIris, don't see a point to leave that issue opened, WDYT?

**Comment by mjoshd** [comment]
No worries, I wasn't sure if it was a Blue Iris v4 vs v5 issue since v5 was released right when I started using it and I had no experience with the previous behavior.

Please consider leaving a note in the MQTT setup section mentioning that if the sensors don't seem to be behaving as expected, tools like MQTT Explorer, MQTT Lens, etc. can be very helpful for debugging.
