### ISSUE TITLE
cannot update from v1.0.7 to 1.0.8 9 or 10

### ISSUE THREAD

**Issue by cabmeeting1** [elad-bar/ha-blueiris#150]
I am unable to update via HACS, previously I just hit the update button in HACS, restart home assistant and blue iris is updated. 
Today I cannot get past anything beyond 1.0.7 . I tried uninstalling the repository, reinstalling,  etc. 
It looks like the update is working when I hit the update button in HACS. but as soon as I restart it is still at 1.0.7 and prompting me to update.  anyone who experienced this problem? Any assistance would be greatly appreciated.

**Comment by kramttocs** [comment]
Anything in the logs? What if you choose the Redownload option and select 1.0.10?

**Comment by cabmeeting1** [comment]
thanks for the response, Yes I tried redownload and tried clean slate as if im installing for the first time.  
 I tried to update again and recreate the problem scenario. There is no error message in the logs just typical warning such as "2022-03-04 09:57:36 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant"   which is the same as all HACS integration. 
I also tried restoring back to my older backups dating back to 1 month ago the issue persist.  

[https://imgur.com/hvRqVJa](url)

**Comment by kramttocs** [comment]
I do see that the manifest file still shows 1.0.7. That's my miss - learning as I go here. What's odd though is that I was able to upload without issue.
If you are starting fresh it should pull 1.0.10 by default and no need to upgrade.
If you go into Dev tools >Services do you see the Trigger Camera and Move to Preset services?

**Comment by cabmeeting1** [comment]
I tried to install fresh again. Yes it pulled the 1.0.10  but after seemingly successful installation. I cannot see blue Iris as an added repository.   I went to integration and able to add Blue Iris integration , which means the repository has been added even though I cannot see it in HACS (integration).   I logged in my credentials and success, however there is no devices or entity discovered.  
I went to Dev tools > Services  i can see "Blue Iris NVR: Trigger Camera"  and "blueiris.move_to_preset"  now.  But previously when it was working on my older backups v1.0.7  I didnt see it in services.    It seems installed but no devices or entities and I cannot see it in hacs as installed repository. 
https://imgur.com/a/vxwZh1I

**Comment by kramttocs** [comment]
You'll need to turn on Debug logging via the Configure option in the integration and see if anything shows up in the Full log.

**Comment by cabmeeting1** [comment]
thanks, I enabled debug and then restarted and now seeing related errors in the log:

Failed to update, step: Start updating domain binary_sensor, Error: 'binary_sensor', Line: 197
6:18:20 PM – (ERROR) Blue Iris NVR (custom integration)
Unable to prepare setup for platform blueiris.binary_sensor: Platform not found (No module named 'custom_components.blueiris.binary_sensors').
6:18:20 PM – (ERROR) setup.py
Error handling request
6:17:55 PM – (ERROR) Blue Iris NVR (custom integration)
Failed to load BlueIris, error: Unable to find service logger.set_level, line: 27
12:02:30 PM – (ERROR) Blue Iris NVR (custom integration)

https://imgur.com/a/pCB7DVn

**Comment by kramttocs** [comment]
Thanks.
The cause for the logger.set_level error is that it Logging isn't turned on in HA so that service doesn't exist.
In your configuration.yaml add this:

logger:
default: warning

Save and restart. You can set the default to another level if you'd like.
Do note that if you change the log level via the Blue Iris options back to Default (after we solve this issue :) ) you will need to restart HA.

For the other, I don't know why it's missing files and not installing from HACS fully. My recommendation would be to pull the code from this repo and manually copy the bluiris folder from custom_components into your HA install.

**Comment by kramttocs** [comment]
I also just updated the manifest.json version so we'll be able to test/eliminate that as well. From the HA doc it shows it's required but I am not seeing anything related to how it is used. Obviously not to identify updates. So maybe feature flags?

**Comment by cabmeeting1** [comment]
thank you for your prompt response. I did have filtered logger all along before the problem started. I just disabled them very recently to allow the logs to capture blue iris logs.   I added back the below today. 
logger:
default: warning
then reinstalled again. Same behavior every time.  a.) I am able to add the blue iris repository, seemingly installing OK, but after installation, it is not showing up as installed integration.   b.) I can go to integration and add Blue Iris, the fact that it's there it means the repository have been added. c.) I can configure successfully but no devices or entities are shown.     after I restart when I hit configure, it seems seeing the components from blue iris it is just not presenting it as entities or devices.  

I did pull the code from the repo and manually copied the Blue iris folder from custom_components into the HA install overwrite, and delete and copy new no luck as well.     Any clue how did it happen suddenly is it related to Home assistant update,  It was perfect up until v1.0.7 I just update in HACS and all works flawlessly.   by the way I'm using HomeAssistant OS v-2022.3.1

**Comment by kramttocs** [comment]
Sorry, I really don't know what's going on there. It still appears like it can't find certain files in the integration.
None of the changes I made in 8,9,10 dealt with the creation of devices/entities.
Can you pull the code from the 1.0.7 release and manually install that? If that doesn't work, I am at a complete loss.

**Comment by cabmeeting1** [comment]
Hello, I resolved the issue in another way.    I just installed my home assistant as clean-slate and started all over again.  Everything is working fine and updating normally as it should.  Thank you for developing this amazing add-on and thank you for providing assistance.

**Comment by kramttocs** [comment]
Haha that's one way to take care of it.
I can't take any credit for creating it though- that's all elad-bar. Since he switched security software and no longer has the ability to maintain/test BI, I am just trying to keep this one going as I am a big fan of it.

**Comment by cabmeeting1** [comment]
haha in that case, thanks for your assistance and thank you heaps to elad-bar  for creating this amazing add-on that makes buying blue iris worth every single penny!
