### ISSUE TITLE
devices not available after update 1.0.10 to 1.0.11

### ISSUE THREAD

**Issue by nrpetonr** [elad-bar/ha-blueiris#152]
after the update from 1.0.10 to 1.0.11, the devices are not more available. i tried remove and add integration again, it does connect to the server, but no devices. after downgrading to 1.0.10, everything is OK again.

**Comment by kramttocs** [comment]
Hey. Can you turn the logging to debug and provide the log? If you delete and re-add the integration, do they show? Please capture the log before trying this.
Thanks

**Comment by kramttocs** [comment]
And in Blue Iris, what is the value of the System Name in Options?

**Comment by nrpetonr** [comment]
does it log also any sensitive private data, .e.g passwords, etc?

**Comment by akerrichardt** [comment]
Same problem here works when moved back to 1.0.10.

**Comment by kramttocs** [comment]
The cause for the logger.set_level error is that it Logging isn't turned on in HA so that service doesn't exist.
In your configuration.yaml add this:

logger:
default: warning

Save and restart. You can set the default to another level if you'd like.
Do note that if you change the log level via the Blue Iris options back to Default (after we solve this issue :) ) you will need to restart HA.

**Comment by nrpetonr** [comment]
figured out meanwhile :-) find the log in my previous post.

**Comment by kramttocs** [comment]
Thanks! I'll take a look this afternoon.

**Comment by kramttocs** [comment]
Can you take the files from here: https://github.com/kramttocs/ha-blueiris/tree/fix-for-1.0.11 and add the log again?
Thanks

**Comment by kramttocs** [comment]
Actually, wait to do that as I have another change I'd like you to test all at once.
Your camera named KrnovPRACOVNA. If you go to the settings of that one and then the Video tab. What radio button is selected for the Device Type?

**Comment by nrpetonr** [comment]
radio button under device type? not sure which setting you mean, there is nothing like that under video - device type. however that camera is **usb, firewire, analog**.

**Comment by kramttocs** [comment]
Here you go: https://github.com/kramttocs/ha-blueiris/tree/fix-for-1.0.11/custom_components/blueiris
Please take the files from there and overwrite yours. The only files you really need are

managers\device_manager.py
managers\home_assistant.py
managers\entity_manager.py
helpers\__init__.py
helpers\const.py

Download these, copy them over your existing ones, restart HA and let me know if it works. You may need to delete and re-add the integration.
Assuming the devices are created you should be able to visit them and see the camera type listed under the name.

**Comment by kramttocs** [comment]
Sorry, yes - on 1.0.11

**Comment by nrpetonr** [comment]
> Sorry, yes - on 1.0.11

it is working. good job, thx

**Comment by kramttocs** [comment]
Great! I'll get this pushed out as soon as I run a few more tests. Make sure you turn debug off - I added a lot of messages in those files :)

**Comment by akerrichardt** [comment]
Mine is working on 1.0.12.  Thanks

**Comment by kramttocs** [comment]
> Mine is working on 1.0.12. Thanks

Glad to hear it! Sorry about that.
