### ISSUE TITLE
Can't use Local, internal IP address since update

### ISSUE THREAD

**Issue by griffincorriher** [elad-bar/ha-blueiris#153]
Reinstalled integration and now I can not login using internal IP, but can using external. Not sure what has changed to cause this. SOLVED: it used serverIP:port instead of the internal IP listed in Blue Iris

**Comment by kramttocs** [comment]
Thanks - I will test this out later.

You are back up and going with all cameras showing?

**Comment by griffincorriher** [comment]
Yes I had to use the HA server IP instead of the local BI IP

**Comment by kramttocs** [comment]
Ah. I believe you mean the BI server IP and not the HA server. My guess is that the Adaptor chosen for the "Local, internal (LAN) access" in BI isn't set to the right one. You could change the dropdown to be the right one but it really won't matter unless you have 'Bind exclusively' checked.

Glad to hear you are up and going!
Let me know if you come across anything else.
