### ISSUE TITLE
Error adding new Camera to Blue Iris integration

### ISSUE THREAD

**Issue by gilkjame** [elad-bar/ha-blueiris#157]
I added a new camera in BI.  when I go to add it to the integration in HA, I select the new camera from the configuration dropdown and when I click submit, I get the following error:

User input malformed: NDrive is not a valid option for dictionary value @ data['allowed_camera']

The camera is configured the same way as my other cameras in BI.  
Any guidance on what to look at would be appreciated.
Jim

**Comment by gilkjame** [comment]
I ended up deleting the integration and reinstalling it.  now i am getting an invalid server details error.  nothing has changed on my BI server.  not sure what the issue is.

**Comment by kramttocs** [comment]
Anything showing in the logs? When is this error being seen?

**Comment by gilkjame** [comment]
log shows failure to access BI server:
This error originated from a custom integration.

Logger: custom_components.blueiris.managers.config_flow_manager
Source: custom_components/blueiris/managers/config_flow_manager.py:442
Integration: Blue Iris NVR (documentation)
First occurred: 8:20:03 AM (1 occurrences)
Last logged: 8:20:03 AM

Failed to access BlueIris Server (192.168.1.97)

**Comment by gilkjame** [comment]
yeah...all info was correct.  good call on looking at BI logs.  looks like a profile is restricting access...need to dig into that...

**Comment by gilkjame** [comment]
found the profile restriction and removed it.  was able to reinstall the integration and my new camera is not accessible.  this still does not explain why I could not see the new cam after adding it in BI.  oddly, I was able to see 4 sensors from that camera in HA, but not the main camera sensor.

**Comment by gilkjame** [comment]
I think as I was troubleshooting my original error of not being able to add the camera, I may have inadvertently restricted the active profile for my home assistant user in BI.  the BI log showed and access error based on profile restriction, so it was easy to diagnose.  I removed the profile restriction from my HA user and the connection was successful.

I have plans to add more cameras in the near future, so I will report if I see the same error I originally posted.

**Comment by kramttocs** [comment]
Pre-release: https://github.com/elad-bar/ha-blueiris/releases/tag/v1.015

**Comment by kramttocs** [comment]
https://github.com/elad-bar/ha-blueiris/releases/tag/v1.0.15
