### ISSUE TITLE
BlueIris intergration stopped working 

### ISSUE THREAD

**Issue by Lepelot** [elad-bar/ha-blueiris#158]
Hello, 
After a year of reliable service, my Blue Iris integration stopped working a few days ago. When I first updated to HA 2022.3, last week, I could see my cameras in the new multimedia tab, but then I noticed that they disappeared after a couple of days and my integration was empty (no entities). I decided to restart and update BI and now my integration is showing only a few entities. I also tried to reload the BI integration, but that didn't fix it. 
Am I the only one?

![BI integration](https://user-images.githubusercontent.com/76974827/157841314-f74de827-782b-413c-86eb-bb15141e46d9.gif)
![HA setup](https://user-images.githubusercontent.com/76974827/157841320-b54d7893-313a-42a0-b2a9-fe2bade2798f.gif)

**Comment by kramttocs** [comment]
Please turn on debug logging and provide the log. Thanks

**Comment by Lepelot** [comment]
Hi, thanks for your response. I am not too familiar with debug, but this is what I added to my config file: 

logger: 
  default: debug
  logs:
    custom_components.blueiris: debug

... and, after restart, I got the attached home-assistant.log: 
[home-assistant.log](https://github.com/elad-bar/ha-blueiris/files/8232540/home-assistant.log)

His this what you were looking for?

**Comment by kramttocs** [comment]
Thank you.
For some reason github dropped the 1.0.12 release that fixes this error. I just republished it. Please 'Update Information' in HACS for the integration and take the update.
Let me know if you are back working after doing so.

**Comment by kramttocs** [comment]
Excellent. Thanks for reporting back.
No idea why github dropped that release.
