### ISSUE TITLE
Unable to Install HA-Blue Iris

### ISSUE THREAD

**Issue by L84Q6eDbVI5MqxQ** [elad-bar/ha-blueiris#161]
I just recently set-up Home Assistant OS. 
However, I'm unable to get HA Blue Iris NVR to install on my HA using the download repository inside HACS. 
I've tried to download various versions, but the same result.  No pending restarts.

I did various restarts of the core and server. Still no go.
Blue Iris NVR was downloaded and unpacked under "config/custom_components.".

I'm able to download and set-up other integrations outside of HACS.

I appreciate any assistance.
-Rodney

**Comment by kramttocs** [comment]
Does it not show in the HACS installed repos page?  You are adding it as an integration after the install, right?

**Comment by L84Q6eDbVI5MqxQ** [comment]
> Does it not show in the HACS installed repos page? You are adding it as an integration after the install, right?

I can see it listed as an integration. 
<img width="1253" alt="Screen Shot 2022-03-14 at 5 51 00 PM" src="https://user-images.githubusercontent.com/101532839/158285029-34d287bc-e6e7-4491-846e-161bdf7f39c6.png">
I click download, wait a few minutes, then it takes me back to dashboard.

**Comment by kramttocs** [comment]
I think your best bet may be to manually install this integration and then open a case with HACS to see if there are any logs that might help. You could check to see if anything is showing in the full HA log already when trying to download.

**Comment by kramttocs** [comment]
Could also manually delete the blueiris folder, restart and try again
