### ISSUE TITLE
New error message. = user input malformed

### ISSUE THREAD

**Issue by kwil2011** [elad-bar/ha-blueiris#162]
User input malformed: Index is not a valid option for dictionary value @ data['allowed_camera']

Everything was working perfectly.  All of a sudden it stopped. 
 
BlueIris version  5.5.5.13

## System Health

version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103
arch | x86_64
timezone | Australia/Brisbane

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4899
Installed Version | 1.22.0
Stage | running
Available Repositories | 1077
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.4
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 9.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), Studio Code Server (4.1.0), Samba share (9.5.1), Terminal & SSH (9.3.0), File editor (5.3.3), SSH & Web Terminal (10.1.0), Node-RED (11.1.0), Duck DNS (1.14.0), Z-Wave JS to MQTT (0.36.0), Z-Wave JS (0.1.54), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 8
views | 11
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by kramttocs** [comment]
You are only getting that error when trying to save the 'Configure' popup, correct?
How has the integration itself 'stopped'?

You should be able to remove and readd the integration but that will also prevent any further troubleshooting so as much information as you can gather before doing so, will be helpful.

**Comment by kwil2011** [comment]
No its doesn't come up at all when I check configuration  and restart home assistant.  It's is there when I open the Blue Iris integration.  The integration no longer shows the camera on the dashboard.  And motion triggers etc don't work. 
The log error says.
Failed to connect http://192.168.*.*/Jason, Error: Cannot connect to host 192.168.*.*:81 [Connect call failed ('192.168.0.89',81)], Line :84
17 March 2022 23:06:48 -(ERROR) Blue Iris NVR (custon integration)

Unable to find referenced entities seitxh.blueiris_profile_home (warning) helpers/service.py

**Comment by kramttocs** [comment]
Ah, that indicates a network connection issue between HA and you BI server. Check the logs in BI and ensure you can connect from your HA environment. You should see a user login attempt in the BI console. If not, then it can't even make it there.

**Comment by kwil2011** [comment]
Having said that.. the ip address it is saying does not exist.  But when I go to the integration and try update it that's when I get the first error.  It won't let me update.

**Comment by kwil2011** [comment]
Yeah. There is no sign in the BI logs that HA is even connecting

**Comment by kwil2011** [comment]
![Screenshot_20220318-081239_Home Assistant.jpg](https://user-images.githubusercontent.com/74435891/158902991-1588dcf9-9850-4d75-86cf-8ce53a755b57.jpg)****

From memory this should be the BI IP address?

**Comment by kramttocs** [comment]
Yep, if the IP changes that would break the entities from updating. You'll want to make sure the BI server is static. Correct - the IP the integration needs is the BI server IP. The error is a bug I am trying to track down but you can get up and going by either setting the BI server IP to that one (and make it static) or you can delete and add the integration back.

**Comment by kramttocs** [comment]
Since this was due to your BI server IP changing, I am going to go ahead and close it out. The error preventing the configuration from being able to be modified is an issue already reported. 
Thanks
