### ISSUE TITLE
How to get audio from the camera?

### ISSUE THREAD

**Issue by HairyHook** [elad-bar/ha-blueiris#166]
Hi there,

I can't figure out how to get audio in the camera streams. Looking at all my camera attributed in HA, Audio Support is set to true. Any help is very much appreciated. 

Thank you!

**Comment by kramttocs** [comment]
Hey,
The best bet would be to try this outside of the integration. Meaning setting up the camera manually. That way we can determine if it's an HA thing or an integration thing. I've never actually tried to get audio working myself.
Here is some info that makes it sound like it should be working in HA now: https://community.home-assistant.io/t/streaming-cameras-with-audio/223035
Let me know what you find out!

**Comment by HairyHook** [comment]
Thanks for your quick answer! I have tried adding the camera manually as a generic camera and audio is working. Also, I tried adding the camera directly from BI as a generic camera (rtsp://<BI_IP:port>/<cam>) and audio is working as well. When I open the camera created by the integration, I get no volume icon.

**Comment by HairyHook** [comment]
FYI, HA Stream component is picky with audio codecs, but seems to work fine with AAC. HA-blueiris is not outputting any audio.

**Comment by kramttocs** [comment]
Excellent. Appreciate the tests. I'll poke around and see what I can find in the integration.

**Comment by EthanKC** [comment]
Was this ever resolved? I'm in the same boat: audio works with other integrations, but not the BI

**Comment by kicker10BOG** [comment]
Any update on this? It would be really nice if the integration could have audio working too.

**Comment by kramttocs** [comment]
@kicker10BOG That's good to hear. So you just checked that, restarted, and then if you go to the Camera device and click on the sensor with the video, it shows the audio icon?

Or did you add something to Lovelace to see it?

I just tried but am not getting an audio icon from the device/sensor popup window.

**Comment by kicker10BOG** [comment]
@kramttocs I checked it and restarted Home Assistant then clicked on a camera and the popup had the audio icon and played audio as I watched the video.

**Comment by kramttocs** [comment]
Thanks! I needed to clear my browser cache. Then it worked. Will close this out.
