### ISSUE TITLE
Cycle only specific cameras (group)?

### ISSUE THREAD

**Issue by philhzss** [elad-bar/ha-blueiris#167]
Hi,

Is it possible to cycle only cameras in a certain group?

I have a group in Blue Iris called "exterior". I can see it in this I integration and if I add it I get the "all exterior cameras" view, but there is only a "all camera cycle" option for all the cameras, not for the group's cameras. 

Do you know if it's possible to do what I'm trying to do??

Thanks!!

**Comment by kramttocs** [comment]
Hi,
Yes, it is. Had to play around just now to figure it out myself :)

In BI, go to the group (drop down at the top of the cameras towards the right), and then click the gear icon next to the dropdown.
Check the 'Enable camera auto-cycle stream' and save.
You should now be able to add the new 'camera' by going into the Configure settings inside the Blue Iris NVR integration in Home Assistant.

Thanks

**Comment by philhzss** [comment]
Oh thats neat! It worked. Thank you very much for taking the time!!
