### ISSUE TITLE
Integration uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by tankdeer** [elad-bar/ha-blueiris#170]
I am getting warnings in my log about using a deprecated method. 

`2022-06-01 13:15:10 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated 'async_get_registry' to access entity registry, use async_get instead. Please report issue to the custom component author for blueiris using this method at custom_components/blueiris/managers/home_assistant.py, line 96: self._entity_registry = await er_async_get_registry(self._hass)`

Hopefully this can get addressed despite not technically being maintained anymore.

**Comment by kramttocs** [comment]
Thanks. Confirmed the same (seeing it with a few of the integrations I am using). 
I'll get this looked at.

**Comment by kramttocs** [comment]
Thanks @elad-bar !

**Comment by WolfsWelpe** [comment]
Hello I just installed v1.0.14, sadly im still receiving those errors in my log?
`Detected integration that uses deprecated async_get_registry to access entity registry, use async_get instead. Please report issue to the custom component author for None using this method at custom_components/None/managers/home_assistant.py, line 96: self._entity_registry = await er_async_get_registry(self._hass)`

**Comment by kramttocs** [comment]
Are you sure it's from blueiris? The error says 'None' for the component name.

**Comment by WolfsWelpe** [comment]
> Are you sure it's from blueiris? The error says 'None' for the component name.

Hello,

sorry my bad, it was from blueiris indeed but somehow when I updated it just moved the old version to folder "None" and created a new blueiris folder instead of replacing the old one. I just deleted the None folder and its gone. Stupid me could get on this on my own....
