### ISSUE TITLE
No local access to cameras

### ISSUE THREAD

**Issue by Madbeefer** [elad-bar/ha-blueiris#173]
I am unable to use the integration if I try to access my blue iris server from the local IP. I can use it if I use my remote IP.. This has been going on for a while, I figured it was something BI did with an update and it would get taken care of eventually. If I am the only one having this issue then I would guess its something on my network side, but I haven't changed anything in quite some time...

**Comment by kramttocs** [comment]
Hey @Madbeefer ,
I am using my local IP without issue so I would agree this is something with your config. You can take a look at the link below for some setup instructions. If you find that there is a gap in the integration that should be working with your config, please provide the details needed to replicate and it might be able to be added.

https://github.com/elad-bar/ha-blueiris/blob/master/docs/blueiris-server.md

Thanks

**Comment by Madbeefer** [comment]
Looks like somehow blue iris reset some security settings and that was giving me my issues.. thanks for the link.
