### ISSUE TITLE
Camera rename, camera component error in HA

### ISSUE THREAD

**Issue by tylerwatt12** [elad-bar/ha-blueiris#175]
After renaming a camera in BI, the old camera name still shows in the "options for blue iris" page of the BI Integration.
I am unable to deselect the old camera name, and unable to change any settings because when I hit save, i get an error:

User input malformed: LivingRoom is not a valid option for dictionary value @ data['allowed_camera']

Where LivingRoom is the old camera name.

I know resetting the plugin would probably fix this, but I wanted to bring it to your attention.

<img width="591" alt="Screen Shot 2022-07-05 at 11 41 07 AM" src="https://user-images.githubusercontent.com/1408304/177366051-f0a7e4fc-e862-44ef-91e5-5f02961bb9ab.png">
<img width="586" alt="Screen Shot 2022-07-05 at 11 41 17 AM" src="https://user-images.githubusercontent.com/1408304/177366054-b11e1cc5-6588-410a-8d56-3879db37b672.png">

**Comment by kramttocs** [comment]
Thanks. I've seen this one myself but haven't tracked it down.

https://github.com/elad-bar/ha-blueiris/issues/157#issuecomment-1063346286

**Comment by shawnhaywood** [comment]
I'm curious what you did? Did you regenerate config files or reinstall the integration?  I'm having a similar problem with same error message.

**Comment by navydavid** [comment]
I am having this issue as well:

I have several groups that were no longer in Blue Iris after a recent crash. I was able to add those back in Blue Iris, but the camera name changes are still there.

The issue seems to be that we're not able to remove "orphaned" items. They show in the line in the config, but not in the drop down.

**Comment by navydavid** [comment]
I HAVE found a workaround for the issue:
The easy way is to delete the integration and start over, but I found that kind of annoying as I've got a lot of automations on them in addition there's a bunch of HA clean up that would have to occur.

The workaround:
1. I changed one settings and clicked submit. It told me where it was upset. (CameraName) is not a valid entry. 
2. I went into Blue Iris and CREATED that camera, just cloning it of off another camera temporarily. 
3. Restart HA (you can probably just reload integrations)
4. You'll have to do this process a few times, each time you'll find where the "problem object is" sometimes, it's cause you cloned camera doesn't have an audio feed, so you'll need to enable it. Go back and start over.
5. Eventually, you'll be allowed to save the config.
6. THEN you'll to UNMANAGE in HA all the objects you created. (In each section.)
7. Verify that there's no more issues (you can change something on the fly)
8. Then delete everything you don't want in Blue Iris. 
9. Then re-validate.

**Comment by peter--s** [comment]
> Thanks. I've seen this one myself but haven't tracked it down.
> 
> [#157 (comment)](https://github.com/elad-bar/ha-blueiris/issues/157#issuecomment-1063346286)

See https://github.com/home-assistant/frontend/issues/10608, which also features a nice workaround (editing /config/.storage/core.config_entries).

**Comment by kramttocs** [comment]
Pre-release: https://github.com/elad-bar/ha-blueiris/releases/tag/v1.015

**Comment by kramttocs** [comment]
https://github.com/elad-bar/ha-blueiris/releases/tag/v1.0.15
