### ISSUE TITLE
unknow error occured

### ISSUE THREAD

**Issue by abbachia** [elad-bar/ha-blueiris#177]
cannot seem to successfully integrate blue iris...

keep getting unknow error message on login....

any tip to troubleshoot would be appreciated

**Comment by kramttocs** [comment]
Take a look at the guide here: https://github.com/elad-bar/ha-blueiris/blob/master/docs/blueiris-server.md
If that doesn't help, turn on logging and post the relevant output.

**Comment by ultimateguy** [comment]
I just had the same error. The problem was that Windows on my Blue Iris host had the network set as Public, which makes the host undiscoverable. Changing the network type to Private solved the problem.

**Comment by kramttocs** [comment]
Closing due to no reply
