### ISSUE TITLE
Camera images are grayscale with pink and green random areas

### ISSUE THREAD

**Issue by vongyver** [elad-bar/ha-blueiris#178]
As of two days ago, the images from my camera in HASS are showing as grayscale with pink and green random areas.  I have verified they look fine in BlueIris.  When the image first loads it's fine, but after less than a second grayscale with pink and green.  I have also checked this on multiple computers and browsers and have the same result on my iPad in Safari and native application.  

I have BlueIris 3 (latest version, supported) running on a Windows 10 server.  Home Assistant is latest version of Core; all my plugins are up to date as well.  The HASS running on an Ubuntu Ubuntu 20.04.4 LTS Server, is also up to date. 

It does seem to follow some shadowing effect of the house in this image, if that helps ![image](https://user-images.githubusercontent.com/2438602/183304371-f916c296-f2c2-4b16-b333-82c42306c738.png)

Let me know if I can help provide any additional visibility or testing support.

**Comment by kramttocs** [comment]
If you use UI3 does it look correct? The integration hasn't changed so I'd start looking at what changes were made in HASS around that time. Might give some direction.

**Comment by vongyver** [comment]
The UI3 was the same.  That was the odd thing that there were no updates when the behaviour started. I was checking all the cameras in BlueIris and did a typical safe to reset and the imaging effect has stopped.  I had reset them before, but this time worked for some reason.  I would like to have narrowed this down a little more, to be of greater value to someone else reading it. 

Sadly this is a reset it a few times and it may restore itself.  Maybe some corruption on disk or memory that corrected itself with resets. 

Thanks for the quick response and suggestion.  I think we can close this short lived issue.  If we can purge it, go for it.

**Comment by kramttocs** [comment]
I've seen this a few times over the years of using BI. Also have times when they turn almost completely green. This is an issue for BI though and not the HA integration. There is a BI support forum that you might want to post in or search through if the issue doesn't resolve quickly.
Thanks

**Comment by vongyver** [comment]
Thank you for that additional info. It's been stable for me with various
camera and both stock POE and remote connected IP cameras through the NVR.

**Comment by kramttocs** [comment]
You bet! If you do happen to post on that forum or find out more information on it, please report back :)

**Comment by vongyver** [comment]
Will do, thanks!
