### ISSUE TITLE
Can't set targets for automation using Call Service > Blue Iris NVR: Trigger Camera

### ISSUE THREAD

**Issue by NetropyGit** [elad-bar/ha-blueiris#180]
No longer does a list of cameras appear as targets when using Call Service to trigger cameras.  This seems to have happened a few HA updates back.   Previously they could be selected.  I have several existing automations using a Hue outdoor motion detectors to trigger various cams that still works, but I can't edit the target camera(s) or create a new automation since there are no cams listed to select.

![Screenshot 2022-09-04 150235](https://user-images.githubusercontent.com/100463317/188329766-8bb42fb7-8da0-4f37-8144-ad77595e3c45.png)

**Comment by kramttocs** [comment]
This is actual an HA issue. I heard it was supposed to be fixed in the first Sept release.

**Comment by NetropyGit** [comment]
Thanks.  Hopefully they'll correct it.

**Comment by NetropyGit** [comment]
This seems to have been fixed in the latest update.
