### ISSUE TITLE
This integration does not support configuration via the UI

### ISSUE THREAD

**Issue by milkywade** [elad-bar/ha-blueiris#181]
Installed integration through HACS. When then going to settings / integrations / add integration, the following message is shown and the integration refuses to load:

`This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.`

home asisstant (core) log shows: `Sep 08 23:03:56 PIPIPI hass[313785]: 2022-09-08 23:03:56.402 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration blueiris: No module named 'paho'`

Versions:
home assistant version is 2022.9.0 ('core' flavor) - happened also on version 2022.8.1.
OS: raspbian 64 bit debian 11 bullseye
HACS: 1.27.1
Blueiris NVR: 1.0.14

Thank you

**Comment by kramttocs** [comment]
I think this has to do with Mqtt not being installed.

**Comment by milkywade** [comment]
thanks - do you know for sure ? also, would it be the case, the error message is less than helpful

**Comment by kramttocs** [comment]
If I knew for sure I wouldn't say 'I think' :)

**Comment by milkywade** [comment]
i get it, decoding "internet language" is not easy :P

Your hunch proved right, after running `pip3.9 install --upgrade paho-mqtt` the installation completed successfully

**Comment by milkywade** [comment]
comment to the dev team: the error message should be more explicit

**Comment by kramttocs** [comment]
I looked into this a bit and I believe this is actually up to Core to provide a better detail message. It ideally would see what dependencies the integration has and provide friendly warning showing which ones are missing.
