### ISSUE TITLE
Motion binary sensors not updating all of a sudden 

### ISSUE THREAD

**Issue by PMaxx-Gaming** [elad-bar/ha-blueiris#183]
I've tried deleting the integration, removing it from HACS and then reinstalling/configuring it from scratch, but for some reason while my binary sensors show up in HA; they don't change state when there is motion.

I have motion alerts set up in Blue Iris, which are working just fine, and the integration has worked fine for over a year, but recently the motion binary sensors stopped working and I haven't changed anything.

Is this a known bug, or has something changed with the integration?

**Comment by kramttocs** [comment]
Nothing has changed in regard to that. I'd look into your MQTT setup. Maybe install MQTT explorer and make sure BI is sending them as expected.

**Comment by kramttocs** [comment]
Can you elaborate on 'all of a sudden'? What all changed? Just the reinstallation?

**Comment by PMaxx-Gaming** [comment]
I just reinstalled it in hopes that it would fix the issue. I'm not entirely sure when the issue started, as the only binary sensor I use is to trigger a light to come on at my front door when motion is detected between certain time periods, and I'm not generally home during this time.

All I can say for certain is that it _WAS_ working for a long time, and some time fairly recently it's stopped working, when I haven't changed any of my configuration that should have affected it.

**Comment by kramttocs** [comment]
I don't know that I have any motion sensors setup for the cameras in HA but I'll check. Can you confirm that MQTT is getting the message(s)?

**Comment by PMaxx-Gaming** [comment]
I'm installing MQTT explorer now to check that. I also double checked my MQTT config in HA and BI, and they both seem fine

**Comment by PMaxx-Gaming** [comment]
Considering I've never really used MQTT before, aside from following a couple of tutorials for HA, MQTT Explorer seems way over my head... I don't even know where to start with it, unfortunately.

**Comment by kramttocs** [comment]
No worries. I just tested setting it up on a camera that didn't have motion alerts previously and it's working (don't you just love hearing that? :)
![image](https://user-images.githubusercontent.com/11565750/190886287-ccbb7b2c-1986-4ac1-be5d-6bb45f5d49c0.png)

Explorer is really the best option but I don't have it installed at the moment or else I'd try to walk through setting it up so we can see what we need.
Check BI to ensure the MQTT server is setup in the global options and check the camera to ensure the 1) it's getting triggered, 2) the alert is set to send on "triggered' and 3) the 'on alert' and 'on reset' MQTT messages are setup correctly as per the manual here on Github

If those all look good, go to HA and make sure the mqtt integration looks good

Keep me updated

**Comment by PMaxx-Gaming** [comment]
I think there may have been an issue with my Mosquitto Broker addon. I've just reinstalled it, and I'm doing some more troubleshooting now.

**Comment by PMaxx-Gaming** [comment]
I wasn't able to pinpoint where the issue was, so I uninstalled everything MQTT related and reinstalled and configured from scratch. Everything seems to be working fine again now :)

It definitely seems like it was an issue with MQTT on my network though, rather than this integration.

**Comment by kramttocs** [comment]
Good deal
