### ISSUE TITLE
ha-blueiris cannot be set up if Blue Iris webserver is running on port 80

### ISSUE THREAD

**Issue by kurtlieber** [elad-bar/ha-blueiris#184]
Using latest version of ha-blueiris, Blue Iris 5.6.0.11 and HA 2022.9.5

Steps to reproduce:

* Install ha-blueiris on a working version of home assistant
* During setup process, attempt to connect to a Blue Iris web server running on port 80
* Receive [error message](https://i.imgur.com/9kzzDiR.png): "User input malformed: expected str for dictionary value @ data[port]"
* Change the Blue Iris web server to run on a different port (I used 81)
* Change 80 to 81 in the ha-blueiris setup screen - make no other changes
* Hit 'submit' and setup will complete successfully.

**Comment by kramttocs** [comment]
This has been mentioned before though I don't know that it's ever been looked into. I'll have to see if I can get BI going on another machine and set it to port 80.

**Comment by kurtlieber** [comment]
Once I had it up and running on port 81, I also attempted to change it back using the 'configure' option in the integrations screen.  I was able to successfully submit the change to port 80 without the UI throwing an error, but I lost all connections to my cameras.  Ultimately, I deleted and reinstalled ha-blueiris back on port 81 to recover.  

So it appears to be something about the port itself vs. some sort of UI error.

**Comment by clofan** [comment]
Ran into this bug tonight.  You can add the  Integration on port 81 (temporarily change it on BI), then after it's created go back into the settings and change it to 80.  It will save if your server is reachable on 80.  The bug only affects creating the initial configuration

**Comment by kramttocs** [comment]
I looked in the code but didn't see what might cause this. Will dig in again when I can.

**Comment by kramttocs** [comment]
Pre-release: https://github.com/elad-bar/ha-blueiris/releases/tag/v1.015

**Comment by kramttocs** [comment]
https://github.com/elad-bar/ha-blueiris/releases/tag/v1.0.15
