### ISSUE TITLE
cameras groups streaming problems

### ISSUE THREAD

**Issue by andrea-mattioli** [elad-bar/ha-blueiris#187]
Hi, I've a problem with the cameras group streaming, the others single cam works fine, the entity status loops on unavailable and inactive.
During the inactive status i see only the preview cams streaming, during the unavailable even the preview doesn't work.
On BlueIris the group streaming is enable, the are any other options to check?

**Comment by kramttocs** [comment]
Here is what I have and it is working fine:
![image](https://user-images.githubusercontent.com/11565750/203686473-b8a944b5-648f-497d-b322-76f96c535f7c.png)

I will need some more detail to do any further digging. How are you accessing the group in HA, what does the status in BI show, etc.

**Comment by andrea-mattioli** [comment]
I don't know how, probably after the last update of HA it is back to work...
Thanks anyway
