### ISSUE TITLE
Setup failed for custom integration blueiris: No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by RoninATX** [elad-bar/ha-blueiris#189]
Error:
> Logger: homeassistant.setup
> Source: setup.py:230
> First occurred: 10:09:46 PM (1 occurrences)
> Last logged: 10:09:46 PM
>
> Setup failed for custom integration blueiris: No setup or config entry setup function defined.

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by kramttocs** [comment]
Please turn on debugging, repeat the action, and provide the log.
Is this the first time setting up HA BI?

**Comment by RoninATX** [comment]
Thanks for your time - existing HA BI installation that's been running fine for almost a year now. Issue began after one of the recent Core or OS updates (within the last couple weeks).  First noticed this Notification: 
![notification](https://user-images.githubusercontent.com/27863216/204971295-8b24c652-f172-4dc2-a056-c7e62c764447.png)

Which then leads to this CORE log entry:
![core_log](https://user-images.githubusercontent.com/27863216/204971341-dd8e37a0-a466-4b0e-8688-e12f3168a049.png)
And under Integrations I see this, with no option to attempt to "reload" the integration, only disable or delete:
![integration](https://user-images.githubusercontent.com/27863216/204971449-3017ae4d-fe27-41d1-aff2-55acb3eda178.png)

Apologies but I'm not clear on the debugging thing - I added a logger line in the config yaml with the level set to "debug" and then exposed the Full Log on Core and looked for things relevent to BlueIris, and see these entries:
>2022-11-30 23:10:10.392 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```
2022-11-30` 23:31:54.144 INFO (MainThread) [homeassistant.setup] Setting up blueiris
2022-11-30` 23:31:54.144 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration blueiris: No setup or config entry setup function defined.
{"name":"homeassistant.setup","message":["Setup failed for custom integration blueiris: No setup or config entry setup function defined."],"level":"ERROR","source":["setup.py",230],"timestamp":1669872714.1449847,"exception":"","count":1,"first_occurred":1669872714.1449847}
[blueiris](https://github.com/elad-bar/ha-blueiris)` ([Show logs](/config/logs?filter=blueiris))
2022-11-30 23:31:54.154 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140703492445360] Sending [{"id":3,"type":"event","event":{"a":{"persistent_notification.invalid_config":{"s":"notifying","a":{"message":"The following integrations and platforms could not be set up:\n\n - [blueiris](https://github.com/elad-bar/ha-blueiris) ([Show logs](/config/logs?filter=blueiris))\n\nPlease check your config and [logs](/config/logs).","title":"Invalid config","friendly_name":"Invalid config"},"c":"01GK62Q0D28ERANVMH2RRNKX4W","lc":1669872714.146687}}}},{"id":26,"type":"event","event":{"event_type":"persistent_notifications_updated","data":{},"origin":"LOCAL","time_fired":"2022-12-01T05:31:54.151923+00:00","context":{"id":"01GK62Q0D7TFJ0JZN9CWSYR74Z","parent_id":null,"user_id":null}}}]
2022-11-30 23:31:54.156 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140703492445360] Sending {"id":49,"type":"result","success":true,"result":[{"notification_id":"invalid_config","message":"The following integrations and platforms could not be set up:\n\n - [blueiris](https://github.com/elad-bar/ha-blueiris) ([Show logs](/config/logs?filter=blueiris))\n\nPlease check your config and [logs](/config/logs).","status":"unread","title":"Invalid config","created_at":"2022-12-01T05:31:54.151913+00:00"}]}
```

**Comment by RoninATX** [comment]
Hold off on this as it may be my own ignorance - I just happened upon the "Community" tab in Home Assist that is tied to HACS where I guess Blue Iris is installed under, and it's telling me there's an upgrade available from 1.0.7 -> 1.0.14. I'm guessing that might help :) 

I'm still getting used to the new UI - I didn't realize Home Assistant won't recommend those updates under the regular Settings tab like it does for Core and others.  I will confirm and close if latest version resolves.

**Comment by kramttocs** [comment]
Thanks. Was just going to suggest going into HACS > BlueIris NVR and then redownloading it (the three dots in the top right). It almost seems like some files for the component got deleted.

But yes, if you are on 1.0.7 you should definitely upgrade to 1.0.14 :)

Keep me updated.

**Comment by kramttocs** [comment]
Make sure you check out the change log also as some new stuff got added after 1.0.7. Now that winter is here and it gets dark sooner, I hope to take care of some issues and add some more features.

**Comment by RoninATX** [comment]
I'm sort of at a weird stand still with this - trying to Update, the Update button just spun for over 10 min but never finished (HACS normally shows the "pending restart" warning).

So I removed BlueIris NVR all-together, cleared out the folder under custom_components, restarted and tired to do a fresh install. Similar outcome - when I press "Download" it just sits there spinning forever:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/27863216/204998313-c135e639-dc90-48b8-9363-ef94590e5cff.png">

As a test, I picked a different HACS repository (iCalendar) and downloaded it.... and it downloaded fine.  Finally, when I go back into the command prompt, I can see that the download process does at least re-create the BlueIris folder and populates it with what I assume is a full playload-
<img width="673" alt="image" src="https://user-images.githubusercontent.com/27863216/204998724-a5d2c2f5-fe6d-406c-8f60-428406634b4b.png">

So it's almost like it's just missing the hand-off back to HACS to say it's ready to go? Waiting 15+ min, still doesn't show up under HACS integrations:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/27863216/204999043-9b15d359-7c53-49ec-8653-3c915faf1ae0.png">

HACS itself showing v1.28.4
<img width="201" alt="image" src="https://user-images.githubusercontent.com/27863216/204999272-4dc104dc-c3c7-46c5-bb7d-a36c1778ef51.png">

What might I be missing?

**Comment by kramttocs** [comment]
The download/install of the package is handled by HACS so you might have some luck posting in their repo. Afraid I can't do anything to help with that part of it.

**Comment by RoninATX** [comment]
Closing this issue and chalking it up to "corrupt Home Assistant". I ended up rebuilding my HA VM and this time around everything installed flawlessly (HACS, Blue Iris NVR, all the cameras, etc) Appreciate the help regardless!

**Comment by kramttocs** [comment]
Great! Though sorry you had to do all that. Thanks for reporting back.
