### ISSUE TITLE
Camera movement sensors never triggered

### ISSUE THREAD

**Issue by chjohans** [elad-bar/ha-blueiris#196]
This integration mostly works fine, but there seems to be an issue with the camera motion sensor (the binary_sensor created by this integration for each camera). It will never trigger even when the camera detects motion and triggers one or more alerts in Blue Iris. Not even once have these motion sensors in HA triggered.

Is this a known issue, and could something be done to fix this?

**Comment by kramttocs** [comment]
Have you configured the mqtt alerts in Blue Iris according to the manual referenced in the documentation?

**Comment by kramttocs** [comment]
https://github.com/elad-bar/ha-blueiris/blob/master/docs/blueiris-server.md

**Comment by chjohans** [comment]
Thanks, I also discovered that I need to set up MQTT messaging. Done, and it is all working now! :)
