### ISSUE TITLE
New warning messages in log with 2022.12

### ISSUE THREAD

**Issue by drjjr2** [elad-bar/ha-blueiris#197]
Since updating this morning I see several instances of these log messages:

> 2022-12-08 21:10:03.919 WARNING (MainThread) [custom_components.blueiris.api.blue_iris_api] Request #0 to BlueIris (http://192.168.0.10:81) failed, Data: {'cmd': 'camlist', 'session': '7b6454ea32da28f43d431370347d4daa'}, Response: {'result': 'fail', 'session': '7b6454ea32da28f43d431370347d4daa'}
> 2022-12-08 21:10:04.092 WARNING (MainThread) [custom_components.blueiris.api.blue_iris_api] Request #1 to BlueIris (http://192.168.0.10:81) failed, Data: {'cmd': 'camlist', 'session': '7b6454ea32da28f43d431370347d4daa'}, Response: {'result': 'fail', 'session': '7b6454ea32da28f43d431370347d4daa'}

**Comment by kramttocs** [comment]
I just set mine to Debug ( integration > configure) and reloaded. I am not seeing that failure.
Can you set yours to debug, reload it and watch the logs?
You should see a cmd:login that fails followed by a success login and then (after some messages) a camlist cmd.

**Comment by kramttocs** [comment]
Thanks. Will close this but report back if they show up again.
