### ISSUE TITLE
custom_updater

### ISSUE THREAD

**Issue by k1ng440** [elad-bar/ha-blueiris#2]
How to install this using custom_updater?

https://github.com/custom-components/custom_updater

Thanks

**Comment by elad-bar** [comment]
Thanks for sharing the link, I'll add support and from the next version it will be supported (probably during the weekend)

**Comment by elad-bar** [comment]
@k1ng440 , please use it by add to custom updater:
  track:
    - components
  component_urls:
    - https://raw.githubusercontent.com/elad-bar/ha-blueiris/master/blue_iris.json
  
Note that the previous version doesn't contain VERSION, which means you need to pull and next update it will grab it using custom updater
