### ISSUE TITLE
"Invalid server details" since BlueIris password change

### ISSUE THREAD

**Issue by EpicLPer** [elad-bar/ha-blueiris#203]
Heya!

Ever since I changed my password on BlueIris I'm getting a "Invalid server details" error when trying to, at first, edit the Integration and now trying to freshly re-add it after removal.

The Log outputs are either of these when I try:
`Failed to access BlueIris Server (IP Address redacted)`
`Cannot complete login`

If there is any better way to provide you with better log outputs or details please say so, thanks :)

**Comment by kramttocs** [comment]
I would check the logs in BlueIris itself. It's saying that the integration can't reach the BI Server so could be IP, port, or your IP/user is locked out.

**Comment by EpicLPer** [comment]
I've tried adding the server via IP multiple times which somehow didn't work, now that I added it via hostname it suddenly worked... not sure why.

Closing this ticket :)
