### ISSUE TITLE
i Get Multiple error Messages

### ISSUE THREAD

**Issue by abeksis** [elad-bar/ha-blueiris#210]
`2023-06-08 17:49:55.199 ERROR (MainThread) [homeassistant.util.logging] Exception in state_message_received when handling msg on 'BlueIris/Gate/Status': '{ "type': "MOTION_A", "trigger": "ON" }'
Traceback (most recent call last):
  File "/config/custom_components/blueiris/binary_sensors/main.py", line 57, in state_message_received
    self._state_message_received(message)
  File "/config/custom_components/blueiris/binary_sensors/main.py", line 70, in _state_message_received
    payload = json.loads(message.payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 12 (char 11)`

**Comment by abeksis** [comment]
thank you for the answer.

I do not use TYPE. Here's my code, I think there's some bug.

`---
title: Securing
path: securing
icon: mdi:cctv
type: custom:grid-layout
badges: []
cards:
  - type: custom:vertical-stack-in-card
    cards:
      # System cameras
      - type: horizontal-stack
        cards:
          - type: custom:vertical-stack-in-card
            cards:
              - type: picture-entity
                entity: camera.avi_abeksis_all_cameras
                name: All
                show_state: false
                show_name: false                
          - type: custom:vertical-stack-in-card
            cards:
              - type: picture-entity
                entity: camera.avi_abeksis_all_cameras_cycle
                name: Cycle
                show_state: false
                show_name: false
                camera_view: live
      # Blue Iris Armed / Disarm Profiles
      # - type: entities
      #   title: Blue Iris
      #   show_header_toggle: false
      #   entities:
      #     - entity: switch.blueiris_alerts
      #       name: Arm / Disarm

  # Front Door camera
  - type: custom:vertical-stack-in-card
    cards:
      - type: picture-entity
        entity: camera.avi_abeksis_front_gate
        name: Front Gate
        show_state: false
        show_name: false
        camera_view: live
      - type: glance
        entities:
          - entity: binary_sensor.avi_abeksis_front_gate_motion
            name: Motion
          - entity: binary_sensor.avi_abeksis_front_gate_external
            name: external
          - entity: binary_sensor.avi_abeksis_front_gate_connectivity
            name: Connectivity`

**Comment by kramttocs** [comment]
In Blue Iris go to your gate camera and check your mqtt configuration for motion. What I am referring to is this:

{ "type': "MOTION_A", "trigger": "ON" }

Notice that TYPE has mismatched quotes.
Check out the Blue Iris manual here on GitHub if you need a refresher on this functionality.
Let me know what you find.
I believe this is a simple typo in your setup.

**Comment by abeksis** [comment]
Thanks for the response.
This is the code I have under on on ALERT

https://imgur.com/nAs1w3h

and on resat:

https://imgur.com/PoYGfl0

**Comment by kramttocs** [comment]
Thanks for the screenshots. In those you have the single quote after TYPE typo. You need to fix that and all should be well. Closing as such.

**Comment by abeksis** [comment]
thank you for the answer.

Thanks for help and patience.

**Comment by kramttocs** [comment]
You bet! Please let me know if for some reason that doesn't fix it but I feel pretty good that it will :)
