### ISSUE TITLE
Cannot login to webserver from initial setup for intigration.

### ISSUE THREAD

**Issue by Hellmanx** [elad-bar/ha-blueiris#214]
When I provide the correct server details and login info, I will get the error: Invalid server details.
Kinda wish there was a debugger.  The integration seems to try for about 10 seconds until it gives up.

**Comment by kramttocs** [comment]
You can turn on logging and see if that gives you anything. Undoubtedly a network or credential issue as the former is the most common. Please review the guide here in this repo as well as the official Blue Iris doc to ensure your BI instance is accessible. 
Let me know what you find.

**Comment by Hellmanx** [comment]
> You can turn on logging and see if that gives you anything. Undoubtedly a network or credential issue as the former is the most common. Please review the guide here in this repo as well as the official Blue Iris doc to ensure your BI instance is accessible. Let me know what you find.

Nah, something must be wrong with this version.  I had SSL check marked and it shows as false in the logs.

`This error originated from a custom integration.

Logger: custom_components.blueiris.api.blue_iris_api
Source: custom_components/blueiris/api/blue_iris_api.py:131
Integration: Blue Iris NVR (documentation)
First occurred: 7:29:13 PM (2 occurrences)
Last logged: 7:33:20 PM

Failed to connect https://10.0.0.12:444/json, Error: Cannot connect to host 10.0.0.12:444 ssl:False [Connect call failed ('10.0.0.12', 444)], Line: 84`

**Comment by kramttocs** [comment]
Did you try it without ssl?

**Comment by kramttocs** [comment]
> Nah, something must be wrong with this version. I had SSL check marked and it shows as false in the logs.
> 

No, that's not what false means. :)  It means to ignore certificate validation.

**Comment by Hellmanx** [comment]
> > Nah, something must be wrong with this version. I had SSL check marked and it shows as false in the logs.
> 
> No, that's not what false means. :) It means to ignore certificate validation.
> 
> The error that the integration is spitting back is : Failed to connect https://10.0.0.12:444/json,
> 
> The other is from the library it's using. Can you hit that IP from a PC other than your BI machine?

Yep, i can connect to it. I've never really had a problem with the web interface for BI.

**Comment by kramttocs** [comment]
Did you try non SSL just to rule that out?

**Comment by Hellmanx** [comment]
> Did you try non SSL just to rule that out?

Yep, same type of error.

**Comment by kramttocs** [comment]
Ok, that rules that out so I won't try retesting mine using ssl. Nothing looks like a code issue that I can see or have seen in the past. The integration is just unable to connect to the host. It looks like a network thing as a credential issue should manifest differently. What it's trying to do is grab a session id from BI to use. I am unable to really help with network connectivity issues as people have things setup a myriad of ways. I don't know if you read through the guide here and the BI help file I mentioned above but they both have good information about this. 

I'll leave this open for a few days in case you do find something unique in your setup the code should account for. Or just have some questions I can try to help out with.

**Comment by ingus16** [comment]
Hi , did this thing has been sorted ? I have the same issue.

**Comment by kramttocs** [comment]
Great!
