### ISSUE TITLE
Connectivity Sensors Do Not Work

### ISSUE THREAD

**Issue by shahmirthesquid** [elad-bar/ha-blueiris#215]
Hi, the connectivity sensors for the cameras do not work. I have been facing some disconnection issues with one of my cameras, so I tried to use home assistant's history function to check the connectivity history of the camera. The connectivity sensor shows that the camera has always been connected. When I explicitly unplugged the camera, blue iris clearly showed "camera failed to connect" but the connectivity sensor in home assistant still shows it as connected.

I believe this is happening cuz this plugin is making a depreciated JSON API call to the blue iris server. I am unfamiliar with this codebase, but have a lot of experience with the blue iris JSON API. If someone could just tell me which source file deals with the connectivity sensor, I am sure I could fix this problem myself and submit a merge request.

**Comment by kramttocs** [comment]
The sensors require mqtt setup and configuration. Have you gone through that process? If not, please review the guide here in the repo.

**Comment by kramttocs** [comment]
Great! Glad it's working.
I think using that attribute is a great idea (assuming it actually represents what is seems like it should). If you want to poke around in the code, by all means please do.
I've made some changes and added some functionality in this repo (and try to help with issues reported) but haven't fully wrapped my head around the camera level sensor workings.
