### ISSUE TITLE
Config Flow error with 2024.1.bX

### ISSUE THREAD

**Issue by reotto613** [elad-bar/ha-blueiris#218]
I loaded the beta of HA 2024.1.bX, and my cameras stopped working. I deleted the integration, and now it will lot load.

The error when I try to install it is:

Error

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

The error in the logs is:

![IMG_1846](https://github.com/elad-bar/ha-blueiris/assets/60767748/92438c53-fdb9-4011-b6ae-a6630c9dd65f)
![IMG_1847](https://github.com/elad-bar/ha-blueiris/assets/60767748/6ad36aa3-d742-41b9-b867-027982ae11f7)

**Comment by kramttocs** [comment]
Do you see the same with the latest non-beta?

**Comment by reotto613** [comment]
Nope 2023.12.X works just fine. 

I posted this issue as part of HA Core and they said they made changes, and never anticipated that configuration flow would be done this way or they likely would have given custom repositories a heads up. It wasn’t specific what was meant. Here is a link to that issue:

[https://github.com/home-assistant/core/issues/106714#issuecomment-1872512955](url)

**Comment by elad-bar** [comment]
In HA 2024.1.0 new breaking change introduced for dataclasses,
Will fix it, only constraint, fix should be available only for 2024.1.0b0 and above

**Comment by kramttocs** [comment]
> Nope 2023.12.X works just fine.
> 
> I posted this issue as part of HA Core and they said they made changes, and never anticipated that configuration flow would be done this way or they likely would have given custom repositories a heads up. It wasn’t specific what was meant. Here is a link to that issue:
> 
> [home-assistant/core#106714](https://github.com/home-assistant/core/issues/106714)

Thanks! Looks like elad-bar is already aware of it but just for future reference of any bug reports for anything, please include context like this in the initial report. :)

**Comment by kramttocs** [comment]
> In HA 2024.1.0 new breaking change introduced for dataclasses, Will fix it, only constraint, fix should be available only for 2024.1.0b0 and above

You think it's the dataclasses change and not this one dealing with minor versions (only mention due to the comment in the core issue: https://developers.home-assistant.io/blog/2023/12/18/config-entry-minor-version/ ?

**Comment by elad-bar** [comment]
you are right, it's not the dataclass but will take a look into it

**Comment by elad-bar** [comment]
@kramttocs please review PR #219,
if it works, please create a release out of it and it will be available only for HA v2024.1.0b0 and above

**Comment by kramttocs** [comment]
Thanks as always @elad-bar !
@reotto613 - 1.0.16 is out there. You may have to click 'Redownload' in HACS if it doesn't show up automatically. Please let us know how it goes.

**Comment by reotto613** [comment]
Worked like a charm. Thanks gentlemen.
