### ISSUE TITLE
HA drops BI feed

### ISSUE THREAD

**Issue by KurtaPajama** [elad-bar/ha-blueiris#220]
After a certain number of hours, the BI feed gets disconnected from my lovelace dashboard.
The feed gets greyed out and becomes unavailable.

I'm having to restart home assistant to bring back the feed.

This has been happening for a little over a month, and I also migrated my HA server to a new PC, so I can't pinpoint which HA update has been causing this.

Issue is not in BI, since BI feed is available when it is dropped from HA.

**Comment by kramttocs** [comment]
Duplicate to https://github.com/elad-bar/ha-blueiris/issues/217
