### ISSUE TITLE
Blue Iris login support

### ISSUE THREAD

**Issue by kkellner** [elad-bar/ha-blueiris#23]
Is there plans to try and support Blue Iris authentication? 

My Blue Iris is front-ended with Nginx (reverse proxy).  The Nginx has the cert (by letsencrypt) and is how I access Blue Iris internal or external.   The issue is that from Blue Iris's perspective, the IP address always looks like "LAN" as the external access IP is terminated at Nginx.   So with this setup, there is no way to turn on "Non-LAN only" for login.   If I do, it turns off login for all access, internal or external.

Without some other more fine grained way to tell Blue Iris when to force a login (e.g., always require login from this IP), I'm stuck with having Blue Iris authentication always on.

So, this gets back to the enhancement request....    support for Blue Iris authentication.  Thoughts?

**Comment by elad-bar** [comment]
for me it works with certificate & authentication (LAN without / NON-LAN with), 
Can you provide more information / configuration to better understand the issue

**Comment by kkellner** [comment]
If I set "Non-LAN Only" option as below, it does not prompt to login when I access Blue Iris externally.

![image](https://user-images.githubusercontent.com/9540241/74065169-805f7500-49b1-11ea-8bb2-4e9319723565.png)

This is because all traffic looks internal to Blue Iris.

Here is the flow of traffic for my setup:

External Access (client browser) --> (public IP) Firewall NAT --> (port 443 internal IP) Nginx -->  (port 80 internal IP) Blue Iris

**Comment by mrgadget** [comment]
Stumbled across this while having some issues getting streams going - @kkellner Nginx should support XFF (x-forwarded-for header), and in BI 5 under the advanced button (on the Webserver tab where you make the changes for this app), you can tick the option for `Use X-Forwarded-For headers` and this should fix your LAN/Non-LAN detection issues.

**Comment by elad-bar** [comment]
@kkellner, was the solution above solved the issue you have reported?

thanks

**Comment by kkellner** [comment]
Unfortunately not.   I updated my Nginx to add the `X-Forwarded-For` and turned on `X-Forwarded-For` in blue iris.  That does work, in that I can see the correct remote (or local) IP address coming into blue iris via the `blue iris status` `connections tab`.  So that part is working.  However when I turn on `Non-LAN only` in blue iris, it still prompts for login even when I access locally.  This occurs even if I bypass Nginx and go directly to the blue iris server IP.   

My blue iris has multiple NICs -- but I have it setup to only use 172.20.0.x network and that is the same network my client browser is coming in on.   So I think its a bug in blue iris.   
![image](https://user-images.githubusercontent.com/9540241/75619995-7b20c080-5b40-11ea-9548-ac274b9b25b7.png)

So it would still be helpful if your HA integration could use BI authentication -- but if I'm the only one that has this issue, I can understand that it would not be worth the time to implement.

**Comment by elad-bar** [comment]
For the component your browser is irrelevant,  what range the HA's IP associated with?

**Comment by kkellner** [comment]
@elad-bar the update you made to support session ids is working great!   Thank you so much for adding this support!  You rock!!

**Comment by elad-bar** [comment]
great news!
