### ISSUE TITLE
Integration No Longer Working after HAOS 13.0 Update - HA v2024.8.1

### ISSUE THREAD

**Issue by mllockwood** [elad-bar/ha-blueiris#238]
EDITED:  I have 2 HA instances running at two different locations.  I updated both of them to 2024.8.1 and HA OS 13.0.  **After I updated to HAOS 13.0 is when the issue started.**  Ever since then, it appears that the BI integration no longer works on either of them.  I get "timeout" errors for the video streams, and none of the sensors seem to be providing data from BI to HA.  

v1.0.19 of the BI Integration

Logger: custom_components.blueiris.camera
Source: custom_components/blueiris/camera.py:169
Timeout getting camera image from Driveway

**Comment by kramttocs** [comment]
I can confirm mine (16 cameras) are working as expected as well as triggering and changing profiles. I am not aware of any breaking HA changes so please look at your network or Blue Iris.

**Comment by mag1024** [comment]
Mine just stopped working as well.
I was already running core 2024.8.1, and everything was working fine, but updating to HA OS 13.0, broke it.
Luckily, I had a pre-OS-update snapshot I could revert it, and now everything is working again.
Nothing jumps out at me as suspicious in the [changelog](https://github.com/home-assistant/operating-system/releases/tag/13.0).

**Comment by Nunak** [comment]
Same issue what I see in logs:
```
2024-08-16 06:38:37.202 ERROR (MainThread) [custom_components.blueiris.api.blue_iris_api] Failed to connect http://192.168.1.2:81/json, Error: , Line: 84
2024-08-16 06:38:37.202 ERROR (MainThread) [custom_components.blueiris.api.blue_iris_api] Failed to connect http://192.168.1.2:81/json, Error: Session is closed, Line: 84
```

**Comment by kramttocs** [comment]
Mine are still working fine so not sure what is different without more info. I dont view the streams but enabled one after this was submitted and it's showing fine. Can any of you try changing the stream settings in the config to see if that has any impact?

Are none of your sensors working either? Changing profiles?

**Comment by mllockwood** [comment]
> HA OS 13.0

Yes, it was when I upgraded to HA OS 13.0 when the issues started.  It was not due to the 2024.8.1 upgrade.  I concur with you.

**Comment by mllockwood** [comment]
> Mine are still working fine so not sure what is different without more info. I dont view the streams but enabled one after this was submitted and it's showing fine. Can any of you try changing the stream settings in the config to see if that has any impact?
> 
> Are none of your sensors working either? Changing profiles?

Changing profiles is working fine.
All of the sensors show "became unavailable" any time I start or restart the integration.  
The sensors do not appear to be working at all.  I am not receiving any updates about motion from the cameras in to HA from BI.

**Comment by kramttocs** [comment]
Are these mqtt sensors? Have you confirmed mqtt is working and have you tested that in BlueIris?
Nginx had an issue a couple of days ago - if using that addon, is it on the latest?

Without me being able to replicate, I really am just guessing so I will need your help in eliminating things on your end and troubleshooting.

**Comment by mllockwood** [comment]
> Are these mqtt sensors? Have you confirmed mqtt is working and have you tested that in BlueIris? Nginx had an issue a couple of days ago - if using that addon, is it on the latest?
> 
> Without me being able to replicate, I really am just guessing so I will need your help in eliminating things on your end and troubleshooting.

I am not using any MQTT sensors between BI and HA.  I solely rely on the BI native integration for camera feeds and sensors.

**Comment by kramttocs** [comment]
Please see https://github.com/home-assistant/operating-system/issues/3528

I will close this out based on that but can reopen if something new comes to light.
