### ISSUE TITLE
Integration 'blueiris' calls async_forward_entry_setup for integration, which is deprecated and will stop working in Home Assistant 2025.6

### ISSUE THREAD

**Issue by Benj-HaRRison** [elad-bar/ha-blueiris#245]
Уровень: ПРЕДУПРЕЖДЕНИЕ
Регистратор: homeassistant.helpers.frame
Источник: helpers/frame.py:188
Первое сообщение: 01:09:20 (2 сообщений)
Последнее сообщение: 01:09:27

Detected that custom integration 'blueiris' calls async_forward_entry_setup for integration, blueiris with title: KAVO-2024 and entry_id: 01J8V3F3561XT558GSHXWZBFYM, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/blueiris/managers/home_assistant.py, line 121: await load(self._config_manager.config_entry, domain), please create a bug report at https://github.com/elad-bar/ha-blueiris/issues

**Comment by kramttocs** [comment]
#235

**Comment by kramttocs** [comment]
#235
