### ISSUE TITLE
Integration 'blueiris' calls async_forward_entry_setup for integration

### ISSUE THREAD

**Issue by Benj-HaRRison** [elad-bar/ha-blueiris#246]
Регистратор: homeassistant.helpers.frame
Источник: helpers/frame.py:189
Первое сообщение: 01:45:29 (1 сообщений)
Последнее сообщение: 01:45:29

Detected that custom integration 'blueiris' calls async_forward_entry_setup for integration, blueiris with title: *** and entry_id: ***, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/blueiris/managers/home_assistant.py, line 121: await load(self._config_manager.config_entry, domain), please create a bug report at https://github.com/elad-bar/ha-blueiris/issues

**Comment by kramttocs** [comment]
#235
