### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by kevin182** [elad-bar/ha-blueiris#250]
My issue started off by the integration not getting any new cameras I setup. I could not get them to come down. When I clicked on Configure, I receive the error "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". I could not find any help with this issue online specific to this integration. I tried removing and reinstalling but I get the same error but now it does not show up in the list of integrations. Thank you.

**Comment by kramttocs** [comment]
Please provide the logs

**Comment by kevin182** [comment]
Please forgive my ignorance but which logs do you want? There are no logs for the Blue Iris integration in Home Assistant. Thank you.

**Comment by kramttocs** [comment]
logger:
  default: warning
  logs:
    custom_components.blueiris: debug

Add that to your configuration file (adapt or replace existing), restart, and more logs should show up

**Comment by kramttocs** [comment]
Are you on an old version of HA?
The discovery_keys argument was added in v1.0.20 of ha-blueiris.

**Comment by kramttocs** [comment]
https://github.com/elad-bar/ha-blueiris/issues/240

**Comment by kevin182** [comment]
1.0.21 is what I downloaded through HACS. I get those same errors in #240 but cannot get it to install.

**Comment by kramttocs** [comment]
I mean your HA version (not ha-blueiris). Is it current?

**Comment by kevin182** [comment]
Oh, sorry. I am on 2024.5.4 because I have another issue that many others are having upgrading to the latest. My HA becomes unreachable after I upgrade. https://community.home-assistant.io/t/stuck-at-loading-data-after-updating-core-to-2024-12/805348/46

**Comment by kramttocs** [comment]
In that case, I suspect you'll need to uninstall and pull down an older version of ha-blueiris. I would start at 1.0.19 and work backwards from there if needed.

**Comment by kevin182** [comment]
In researching one of the latest posts in the HA community link above, I saw that Dwain's Dashboard was causing the issue. After removing that, 2024.12.5 now updates and loads fine. Then I update ha-blueiris and it now works too. Thank you. Feel free to close this issue. Happy New Year!
