### ISSUE TITLE
Inivisible Credentials

### ISSUE THREAD

**Issue by MacelinCane** [elad-bar/ha-blueiris#26]
After adding the addong in HACS, not finding the integration to add in Configuration->Integrations->add. 
After some exploration, discovered that when clicking ADD, an empty option was showing
![image](https://user-images.githubusercontent.com/57817530/74209690-d1dc5e00-4c56-11ea-9735-69949935c4ae.png)
When clicked, that empty option opened a familiar dialog, also non-specific.
![image](https://user-images.githubusercontent.com/57817530/74209712-f0daf000-4c56-11ea-8430-b830ef49cca9.png)
However, after guessing and filling out the Blue Iris creds into the super-spy boxes, I got a "success" message that I had indeed installed the blue-iris integration. 
![image](https://user-images.githubusercontent.com/57817530/74209732-02bc9300-4c57-11ea-89dc-4cffb7884fb1.png)

Also, along the way, discovered lots of console errors on this page:
http://hassio.local:8123/config/integrations/dashboard
All items pictured here. 
![image](https://user-images.githubusercontent.com/57817530/74209739-08b27400-4c57-11ea-983e-34e5fd2a8178.png)

Something not completely right there. I also have not gone any further into verifying the install except to verify that the errors on that page no longer show. 
Hope this helps!

**Comment by kummerr** [comment]
I can confirm this is not an isolated issue. I am seeing the same thing.

**Comment by tiaanv** [comment]
Also seeing this...

**Comment by nibotg** [comment]
Hi, having the same problem but I can't click on the empty option to enter the details. When I do it just clears the search and shows the full list of integrations. Tried in Chrome and Opera. Can you advise please ?
Thanks

**Comment by elad-bar** [comment]
@nibotg, Can you post the error from the logs of HA related to the component once you are trying to add and it's being closed?

**Comment by elad-bar** [comment]
@MacelinCane, It seems that .translationz folder is not being downloaded which can explain why you can't see the title of the fields

**Comment by kummerr** [comment]
@elad-bar This appears to be working now... Thank you!

**Comment by MacelinCane** [comment]
> @MacelinCane, It seems that .translationz folder is not being downloaded which can explain why you can't see the title of the fields
> 
> In addition, the console errors are related for the the readme files that has incorrect link when running it locally

Ok. I did verify that the folder did exist in my download, but I did not check to see if it had any content.  I checked (just that it was there) prior to installation.
On the console errors, makes total sense. 

Thanks!

**Comment by iceman73** [comment]
All is working for me now

**Comment by nibotg** [comment]
My issue is also now resolved, I needed to enable MQTT in HA config before trying to connect BI.
Thanks

**Comment by elad-bar** [comment]
Sure, maybe I need to add it to the readme as this is a prerequisite

**Comment by MacelinCane** [comment]
I won't be able to do any further testing for a while, and if I need to I can reinstall it from scratch, but my bet is this is resolved, if you want to close the issue. :)
