### ISSUE TITLE
Profile Switching

### ISSUE THREAD

**Issue by otiswrx** [elad-bar/ha-blueiris#27]
I just updated to the latest release and profile switching does not work anymore. If I try activating a switch in HA it fails and reverts to previous state. If I manually switch in BI, HA doesn't pick up the change.

**Comment by stratplayer** [comment]
Same issue here. Along with the MQTT messages not triggering the Motion Alert either

**Comment by elad-bar** [comment]
Will check it

**Comment by rschmitter** [comment]
My profiles works for a few minutes after each boot and then they stop working.

**Comment by iceman73** [comment]
The newest version, now I dont get the Switches generated at all

**Comment by elad-bar** [comment]
if you don't have the switches, it means you didn't filled-in valid credentials, please share debug level log of the component to find out if that's the cause

**Comment by otiswrx** [comment]
Switches are there for me still after latest update, but only work for a few minutes after HA restart

**Comment by elad-bar** [comment]
Please provide HA pog of the BlueIris component 

Thanks

**Comment by elad-bar** [comment]
no need to provide the logs, I saw the same behaviour you wrote above, checking it

thanks
