### ISSUE TITLE
Generated scripts minor syntax error

### ISSUE THREAD

**Issue by Linwood-F** [elad-bar/ha-blueiris#31]
The generate script builds something like this:

      camera_dropdown: 
        name: BlueIris Camera 
        initial: All 
        icon: mdi:camera 
        options: 
          - +All cameras
          - +All cameras cycle
          - camDriveway
          - camNorthside
          - etc

The "Initial" is not consistent with the options and fails the check configuration.  This was with the version bcc0ec3 (I don't see a version number) that was current as of 2/23/2020 and current blue iris. 5.1.0.1.

**Comment by Linwood-F** [comment]
Additional minor issue: all the generated code lacks the prefix "blueiris_" on the entity names.

Which brings up the question: In order for MQTT motion to work and link to a camera is it necessary to retain the default camera names (e.g. in my case the entity is "Blueiris camDriveway" when the camera in BlueIris is "camDriveway".  I'm not able to test it due to lack of motion MQTT working right now, but can one change the entity name to remove the BlueIris prefix, or will that break such linkage?

**Comment by elad-bar** [comment]
I updated the script generator yesterday, it might work better now,
As for getting MQTT event and bind it to sensor, you don't need to do anything *as long as* the instructions of how to configure it:
Topic - BlueIris/&CAM/Status
Payload - { "type": "&TYPE", "trigger": "ON" }

trigger should be OFF when there is reset event

As for Audio alert - there is just ON event, the component will retrigger itself after 2 seconds of quiet

**Comment by elad-bar** [comment]
Can you check with the latest that it works?

thanks

**Comment by Linwood-F** [comment]
Yes, the scripts now work (+/- indents depending on how you incorporate them). 

The only catch now is that you lost the cast option for lovelace; the inputs and scripts are present but not used.  One minor suggestion there: if you know or can tell what the supported_features are for media players, omit the ones that do not do video (e.g. I have a ton of google minis that show up in the list).  Unless there's some way in which they do camera audio?

I like the picture-glance use, nicely done.

**Comment by elad-bar** [comment]
the supported_features the script is looking for is SUPPORT_PLAY_MEDIA
it basically means that to be able to run the service `media_player.play_media`

I'm still looking for full casting solution for the component

thanks for the feedback
