### ISSUE TITLE
Make MQTT optional

### ISSUE THREAD

**Issue by fotiDim** [elad-bar/ha-blueiris#32]
Very cool component! Thanks for your work. 👏
As a suggestionI wanted to use the component without MQTT just not to have to reconfigure each camera individually in HA. Perhaps MQTT can be optional in that case.

As a side note, if the MQTT add-on is not installed then the configuration popup just never appears. If MQTT is mandatory it should fail more gracefully. Even after enabling it I had to restart HA for the configuration popup to work.

**Comment by elad-bar** [comment]
Thanks for the feedback, will add it

**Comment by elad-bar** [comment]
@fotiDim, please let me know how it works for you

**Comment by webwhiz** [comment]
@elad-bar thanks for the new release. 
I reinstalled everything to see how polished it it. Much better.
I have a problem though -- 
MQTT Listener by BlueIris  is Off and motion entities are created as well with status 'Clear'.

My Hass.io: add-on 'Mosquitto broker' log below is configured and it's working though. Don't see any sensors from BlueIris even though i configured exactly as mentioned in readme. 

1583123026: New connection from 10.0.0.75 on port 1883.
[INFO] found blueiris on Home Assistant
1582842774: New client connected from 10.0.0.75 as BlueIris (p1, c1, k20, u'blueiris').
1582842775: New connection from 10.0.0.75 on port 1883.
[INFO] found iotlink on Home Assistant
1582842780: New client connected from 10.0.0.75 as BIPC (p2, c1, k15, u'iotlink').
1582842813: New connection from 172.30.32.1 on port 1883.
[INFO] found homeassistant on local database
1582842815: New client connected from 172.30.32.1 as auto-xxxxx (p2, c1, k60, u'homeassistant').

**Comment by elad-bar** [comment]
Please go to the to the entities tab (Configuration -> Entities), if you will see those entities with error status, remove the integration and re-add it, it supposed to clean them

**Comment by webwhiz** [comment]
@elad-bar  Don't see any invalid Blue Iris related entries under Entities Tab ( Configuration -> Entities ).  I did get all the motion, connectivity and cams entries and i have a Cycling Cam on lovelace and works good.

I think my problem is - don't see any Blue Iris entities under ... Configuration --> Integrations --> MQTT Mosquito Broker ; this part should be Blue Iris responsibility to push the mqtt data which has watchdog and motion alerts entries right ? i followed the instructions as in readme. I can see the BlueIris client connected to Mqtt broker too in logs and there are motion alerts reported from my cams normally. Just don't see them in MQTT.  thanks.

**Comment by webwhiz** [comment]
@elad-bar I do actually see the motion sensors showing Detected from after update from last evening. So, guess i'm good :) Thanks for the great work. Still don't know why i dont see any mqtt data from blue iris though. 
Will move to exploring using stream and alerts based on motion and maybe object detection. 
Thanks again.

**Comment by elad-bar** [comment]
@webwhiz, the components are not being created by MQTT integration, BlueIris integration creates them, that's the reason why you see them in BlueIris, that's by design.

MQTT integration is mandatory in case you would like to get notifications from the BlueIris as Binary Sensors mostly because the component is relaying on the connection to avoid creating multiple connection and load the CPU

**Comment by elad-bar** [comment]
can we close that issue?

**Comment by igloo15** [comment]
I do have a question here I see sensors in my BlueIris Integration related to connectivity and motion. I have never fully configured the mqtt thing as it was tedious to go through every camera and setup mqtt broadcast.

Are those sensors (Connected and Motion) fake as in they never change because I didn't setup mqtt in BlueIris?

**Comment by elad-bar** [comment]
If you didn't configure it, you will not get event for them and therefore will not be usable,
There is no way to know over API if the triggers set or not,
I thought at somepoint to add in options of the integration ability to exclude binary sensors (in each category - audio, motion and connectivity), switches (profiles) and camera.

Anyway, you don't need to go camera by camera to set it up, you can point to one camera to do all the configuration - in each of the camera go to:
* Camera Settings -> Trigger and click on Sync Camera to X
* Camera Settings -> Record and click on Sync Camera to X
* Camera Settings -> Alerts and click on Sync Camera to X
* Audio alerts - Need to configure per camera (supports audio) to trigger event (will be covered by the one time settings of Camera Settings -> Alerts)
