### ISSUE TITLE
binary_sensor.blueiris gone after e0a2b31

### ISSUE THREAD

**Issue by Linwood-F** [elad-bar/ha-blueiris#34]
This is not affecting me because I was not using it, but after e0a2b31 three entities disappeared: 

    BlueIris
    BlueIris +All cameras cycle Connectivity
    BlueIris +All cameras Connectivity

I think but not sure that the first was the entity that had all sorts of attributes about the BlueIris setup, at least I do not see anywhere to pull those now.  I wasn't using them, and posting this just in case the change was not intentional.

**Comment by elad-bar** [comment]
It was done intentionally :)
the system camera doesn't have connectivity MQTT message, so they were there by mistake
blueiris changed to blueiris_alerts

thanks
