### ISSUE TITLE
Question: binary_sensor motion detected vs camera triggered

### ISSUE THREAD

**Issue by kkellner** [elad-bar/ha-blueiris#35]
This question is likely better asked on a blue iris forum, but I'll try here in case you know...

There seems to be 3 state events in blue iris (as seen by the web UI, screenshot below) per camera.   They are "motion detected", "camera triggered" and "camera recording".    The MQTT event which then feeds into HA's binary_sensor seems to be connected to "camera triggered".   I have blue iris setup to continue recording 60 seconds after no-motion is detected.   Ideally the "motion" event would be connected to the"motion detected" and not the "camera triggered" but that does not seem to be the case as I can see the motion detected icon clear from the BI UI but HA's motion binary_sensor does not clear until the "camera triggered" icon goes away (in my case 60 seconds later).   

I know this has nothing to do with the HA BI integration -- it can only deal with data that BI publishes to MQTT.  Do you know if there is a setting in BI that can send the "on reset" event when the motion is no longer detected (vs camera triggered is clearned)?

![image](https://user-images.githubusercontent.com/9540241/75631351-5c0d4780-5baf-11ea-9f4f-4aaf25a529ef.png)

**Comment by elad-bar** [comment]
In the guideline there is a section of how to configure it by looking for `Binary sensors for motion, audio and watchdog (connectivity) per camera`
there are 3 sections: Motion, Audio and Watchdog

the audio event is the only event that has no reset event, I implemented in the (binary sensor of audio) code of the component to turn it on to 2 seconds and it will automatically turned off.

Please let me know how it works for you

**Comment by kkellner** [comment]
Either I didn't follow your response or it didn't address my issue.    I would like to perform an action when motion is no longer detected, but BlueIris seems to only have a "reset" when it stops recording. Since I have a blue iris configuration that records 60 seconds after motion has stopped, I don't get the 'reset' until 60 seconds after motion stop.   Not a fault of your integration...  it seems to be a limitation of the mqtt blue iris event reset flexibility.  I was just hoping for a workaround.

![image](https://user-images.githubusercontent.com/9540241/77863756-bff05380-71e1-11ea-85d9-4049012b2840.png)

**Comment by elad-bar** [comment]
If you will set it according to the manual (readme),
Once there is motion it will send it with trigger "MOTION_A" while the reset event will be sent with trigger "MOTION", no need to do any other special config

**Comment by kkellner** [comment]
This is just an FYI that I opened a issue report with Blue Iris on motion detected vs camera triggered and MQTT.

---
BEGIN REPORT
---

I have MQTT setup to alert/reset on motion.  I do get the MQTT messages, however the "MOTION_A" type does not come until the camera stops recording and not when motion is no longer detected.  

In other words:

1. When motion is detected, a MOTION_A event is sent to MQTT topic (good)
1. When motion is stopped, a MOTION_A event is NOT sent to MQTT topic (not so good)
1. When camera stops recording (because setup it configured to record 60 seconds after motion stop), a MOTION_A event is sent to MQTT topic (was expecting this in step number 2)

Within the web UI I can see that Blue Iris has the distinction between motion (blue running man) and record.

![image](https://user-images.githubusercontent.com/9540241/78387086-f2ac9a00-759b-11ea-9e93-56d7ae0c94a2.png)

Raw MQTT events:



Motion detected:
```
Message 1 received on BlueIris/frontRoom/Status at 10:40 AM:
{
    "type": "MOTION_A",
    "trigger": "ON"
}
QoS: 0 - Retain: false
```
Recording stops:
```
Message 2 received on BlueIris/frontRoom/Status at 10:41 AM:
{
    "type": "MOTION_A",
    "trigger": "OFF"
}
QoS: 0 - Retain: false
```

Setup for this camera:

![image](https://user-images.githubusercontent.com/9540241/78387113-02c47980-759c-11ea-8dc8-4d27a35c900e.png)

![image](https://user-images.githubusercontent.com/9540241/78387135-0d7f0e80-759c-11ea-9dc1-855dc6288cbb.png)

![image](https://user-images.githubusercontent.com/9540241/78387146-140d8600-759c-11ea-9f94-3b11fac526d8.png)

On reset settings:

![image](https://user-images.githubusercontent.com/9540241/78387150-1839a380-759c-11ea-8594-bfaf2d5c5120.png)

---
END REPORT
---

**Comment by kkellner** [comment]
I never get a `&type = MOTION` MQTT message so I'm guessing the behavior is different between `always record` and `record motion only` -- with the extra twist that I have it continue to record 60 seconds after motion stops.   I'll see what Blue Iris says....   if anything.    I have another Blue Iris issue open regarding a memory leak when MQTT is enabled -- I have not yet heard back from them on that issue.

**Comment by kkellner** [comment]
Response from Blue Iris:
```
The "On Reset" actions are executed with the TRIGGER ends, not the motion.  The motion could potentially start and stop each couple of seconds ... there are no actions executed for this.
```
So there is no way to know when motion ends.

**Comment by elad-bar** [comment]
It doesn't make sense, if BI knows when there is s motion it will also know when there is no motion... must say it's working perfectly for me,
I will send you screenshots of my setting it might solve it for you as well

**Comment by elad-bar** [comment]
Recording settings:
![image](https://user-images.githubusercontent.com/3207137/79456868-ebec4100-7ff7-11ea-9711-6e6557ccf756.png)

Trigger settings:
![image](https://user-images.githubusercontent.com/3207137/79456795-ccedaf00-7ff7-11ea-96cc-3aa628d238ba.png)

On alert
![image](https://user-images.githubusercontent.com/3207137/79456346-0540bd80-7ff7-11ea-948b-e12cf194c510.png)

On reset:
![image](https://user-images.githubusercontent.com/3207137/79456412-243f4f80-7ff7-11ea-80e4-cbc692114453.png)

**Comment by kkellner** [comment]
Yep, that is the issue.  It seem when the camera record is set to "Continuous" record, the MQTT "Motion" trigger stop event follow as expected.  Meaning the stop event occurs immediately after motion stops.

However if you set the camera record to "When Triggered" and set the "Break Time" to 60 seconds, the MQTT "Motion" trigger stop event does not get sent when motion stops, but when the video stops recording, 60 seconds after motion stops.   

Seems like a Blue Iris bug to me or at least a very odd definition of "Motion".   So for my use-case, which is to know when motions stops, the only way is to set a camera to "continuous" record. 

Closing issue from HA plugin as the issue is on the Blue Iris side.  Nothing the HA plugin can do to fix.
