### ISSUE TITLE
Restart of HASS causes all entities to be renamed to defaults

### ISSUE THREAD

**Issue by officiallybob** [elad-bar/ha-blueiris#37]
If I go through the Home-Assistant UI and rename the entities generated by this integration (remove the BlueIris prefix mainly and then update some names for easier use in HA), the next time I restart, the names will be reverted to camera.blueiris_camera_name.

**Comment by sankeerthb** [comment]
yes, can confirm - same issue occurs.

**Comment by elad-bar** [comment]
@officiallybob / @sankeerthb, can you please check that now it works for you?

thanks

**Comment by officiallybob** [comment]
Changed the names of one camera and and did a restart. Things seem to be sticking now. Thanks!

**Comment by kzaoaai** [comment]
Still happening for me even on 1.0.5
