### ISSUE TITLE
Restart of HAss Clears BlueIris Server Devices in Automations

### ISSUE THREAD

**Issue by SuperSuave** [elad-bar/ha-blueiris#38]
Hopefully this makes sense.

I was trying to use the "Device" option while making automations, instead of "State", or "Call Service". Whenever Home Assistant is restarted, the "BlueIris Server" devices are always set to blank in the automations, and break my automations.

I have switched over to using "State" and "Call Service" and the issue has gone away.

Not sure if there's anything that can be done with it, but the "Devices" options are a bit easier to use in some instances.

**Comment by elad-bar** [comment]
Same issue as in #37 , will work on that soon
