### ISSUE TITLE
Error getting new camera image: Cannot connect to host 192.168.x.xx:xxxx

### ISSUE THREAD

**Issue by TheAlphaLaw** [elad-bar/ha-blueiris#39]
I receive thousands of these errors per day. When viewed directly on BlueIris playback is smooth without any lag, when viewed in HA the stream judders, skips and freezes and the following error is received:

Error getting new camera image: Cannot connect to host 192.168.2.xx:xxxx ssl:None [Connect call failed ('192.168.2.xx', xxxx)]

**Amcrest 4K Camera Settings:**
**FPS:** 20
**Resolution:** 1080P
**Max Stream:** 2048kb/s

Nothing I change corrects the HA stream for these cameras. They're all wired via POE to a Edgeswitch 24, no issues handling the load on any equipment.

**Comment by elad-bar** [comment]
the issues is related to the implementation of WebSocket connection of Stream, not related to the component, component just creates the camera entity, playback is by HA

If you will remove the stream: component it will work (that's what i've done)

**Comment by TheAlphaLaw** [comment]
Stream is not enabled in my config.

**Comment by elad-bar** [comment]
What is the CPU level? Can you post screenshots of the camera when it's in normal mode (lovelace) and opened in HA?

Thanks

**Comment by elad-bar** [comment]
@TheAlphaLaw , can you please post the screenshot?

thanks

**Comment by TheAlphaLaw** [comment]
@elad-bar Home Assistant is emulated on the same system as Blue Iris. HA has access to 6/12 threads of the CPU (8700k) which sits around 5 to 10% usage (total system load). I have 8 cameras pulled into HA.

When the cameras are brought into HA, there is judder and tick lag (random). When I view the Blue Iris web server from any other source, the playback is smooth. 

I'm not 100% of what you're asking screenshot wise. Please see screenshots and let me know if that's what you need. You'll notice the "Preload steam" option is available but stream is not enabled in any config. 

![Lovelace](https://user-images.githubusercontent.com/26587248/77870735-d3161a00-7207-11ea-8999-4de0e5c7bc3c.png)
![Lovelace_Open](https://user-images.githubusercontent.com/26587248/77870737-d4474700-7207-11ea-8856-e3c76535c2cd.png)
![HA_Open](https://user-images.githubusercontent.com/26587248/77870738-d4474700-7207-11ea-9673-f80984ec4f37.png)

**Comment by TheAlphaLaw** [comment]
@elad-bar Anything else needed for you here?

**Comment by elad-bar** [comment]
> I'm not 100% of what you're asking screenshot wise.

According to the screenshots you are using `Stream` component (`Preload stream` checkbox),
there is an issue with the implementation of HA WebSocket and as result of that you see that judder and tick lag.
Issues #9 and #47 are exactly about it.

Can you repeat the steps from issue #47 taken by tiaanv?
> one of the attributes of the camera component that being created is the still / stream URL,
you can create a dedicated component (GenericCamera) using those URLs to check how it works without my component

According to tiaanv it was:
> Without your component (as expected). I get the exact same result.

And

> If I open the stream URL directly in VLC, it's the same.... That's interesting..... So this is clearly a BI issue directly...

**Comment by TheAlphaLaw** [comment]
@elad-bar 
How do I disable the stream component? It's not enabled in config and was not enabled manually.

**Comment by elad-bar** [comment]
in case you are using default configuration, you cannot do that,
you need to switch to full configuration mode which you controls exactly what will run

deafult configuration looks like:
```yaml
# Example configuration.yaml entry
default_config:
```
available at:
https://www.home-assistant.io/integrations/default_config/

when it's being loaded it loads also the `stream` component:
```python
"""Component providing default configuration for new users."""
try:
    import av
except ImportError:
    av = None

from homeassistant.setup import async_setup_component

DOMAIN = "default_config"


async def async_setup(hass, config):
    """Initialize default configuration."""
    if av is None:
        return True

    return await async_setup_component(hass, "stream", config)
```

original source code:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/__init__.py

**Comment by elad-bar** [comment]
@TheAlphaLaw any updates?

**Comment by TheAlphaLaw** [comment]
@elad-bar I haven't had a chance to test out this path and I may not. This could introduce issues in the future as the integrations currently loaded under default are not fully documented. I will likely use Blue Iris Web server directly and not integrate into HA at this time.
