### ISSUE TITLE
Q: Consider Per-component Repos?

### ISSUE THREAD

**Issue by darkgrue** [elad-bar/ha-blueiris#4]
I realize you just consolidated your custom components into a single repo, was wondering if you might re-consider? It's not easily practicable to fork a portion of a repo, so contributors to one/few of your components (I have a particular interest in the Blue Iris integration) will have to retain the entire repo, and all issues and PRs will go into the same bucket, regardless of which component they refer to.

It's not unworkable to deal with the monolithic repo, as it's not a large amount of data, but it might be advantageous to split them all out.

**Comment by elad-bar** [comment]
Moved it to dedicated repo, thanks again

**Comment by darkgrue** [comment]
Closed with the creation of the [ha-blueiris](https://github.com/elad-bar/ha-blueiris/) repo. Thank you! =)
