### ISSUE TITLE
Problem with lovelace and Blue Iris component (HACS)

### ISSUE THREAD

**Issue by jjmuriel** [elad-bar/ha-blueiris#41]
Hi,  I have a problem with the Lovelace GUI and the Blue Iris Component installed with HACS.  I get this error: "Custom element doesn't exist: hui-picture-entity-card" (see attached picture) after update to .107.  Know I have .107.4 (HassOS 3.12) and I have the same problem.  What can I do?  Thanks.

<img width="1188" alt="Screen Shot 2020-03-21 at 12 28 22" src="https://user-images.githubusercontent.com/17131600/77232563-b9256900-6b6f-11ea-89ba-db509d896c01.png">

**Comment by elad-bar** [comment]
This is not related to the component, seems like the resources moved location (part of 107) and UI can't find JS files,
Please check console for errors

**Comment by jjmuriel** [comment]
Ok, thank you.
