### ISSUE TITLE
MQTT Issue

### ISSUE THREAD

**Issue by detxm80** [elad-bar/ha-blueiris#42]
hi, i've follow your guide, nice work! 
I've problem with mqtt binary sensot that not change state (motion, audio, connection), and i don't understand how i wrong.

Mqtt server connect right, it's a log of mosquitto:

`1585051xxx: New client connected from xxx.xx.x.xx as BlueIris (p1, c1, k20, u'myuser').`

For example (maybe i don't understand) i've to change anything here? :

```
Topic - BlueIris/&CAM/Status
Payload - { "type": "&TYPE", "trigger": "ON" }
```

Can you help me? (i'm a newbie)
Thanks

**Comment by elad-bar** [comment]
you will need an MQTT sniffer, 
I'm using in my Windows PC - MQTTLens, listens to the broker at the topic i'm expecting it to broadcast and from that point debugging - topic can be BlueIris/# to listen to all topics of all camera

In linux you can use mosquitto_sub:
```
mosquitto_sub -h hostname -u username -P password -t BlueIris/#
```

Please let me know if you see some results

**Comment by detxm80** [comment]
> ```
> mosquitto_sub -h hostname -u username -P password -t BlueIris/#
> ```

i've mosquitto runnin on ha add-on, i've installed mqtt lens and this is result:

message: unexpected stop

**Comment by elad-bar** [comment]
You need to fill in the settings the broker:
![image](https://user-images.githubusercontent.com/3207137/77545179-b8b00980-6eb2-11ea-857d-204ac9b99162.png)

Once configuration set, you should be able to see events:
![image](https://user-images.githubusercontent.com/3207137/77545308-e9903e80-6eb2-11ea-8527-2668becd9c2d.png)

**Comment by elad-bar** [comment]
Another tool for windows is MQTTBox same concept

**Comment by detxm80** [comment]
> Another tool for windows is MQTTBox same concept

get this error, don't understand  why
```
Publish
BlueIris/#
unexpected stop
qos : 0, retain : true, cmd : publish, dup : false, topic : BlueIris/app, messageId : , length : 29, Raw payload : 1171101011201121019911610110032115116111112
```

**Comment by detxm80** [comment]
`Payload - { "type": "MOTION", "trigger": "ON" }

`{ "type": "MOTION", "trigger": "OFF" }

it is right?

**Comment by elad-bar** [comment]
Seems valid, but it seems the broker has kind of issue since it stops once you are subscribing,
You might need to run the broker with higher log level to understand what is wrong

**Comment by detxm80** [comment]
ok, i've set:
logger:
  default: info
  logs:
     homeassistant.components.mqtt: debug

no logs of blueiris mqtt, :( :(

help me please :)

**Comment by elad-bar** [comment]
it should be:

```
logger:
  default: info
  logs:
     homeassistant.custom_components.blueiris: debug
```

**Comment by detxm80** [comment]
`2020-03-28 13:30:44 DEBUG (MainThread) [custom_components.blueiris.blue_iris_api] Full result of {'cmd': 'camlist', 'session': '58801cbc55011872763eXXXXXXXX'}: {'result': 'success', 'session': '58801cbc5xXXXX', 'data': [{'optionDisplay': '+All cameras', 'optionValue': 'Index', 'FPS': 5.0, 'isMotion': False, 'isTriggered': False, 'xsize': 2, 'ysize': 2, 'width': 1280, 'height': 720, 'audio': True, 'group': ['Sala', 'Cameretta', 'Garage'], 'rects': [[2, 2, 634, 358], [642, 2, 1274, 358], [324, 362, 956, 718]], 'newalerts': 0, 'lastalert': -1, 'alertutc': 0}, {'optionDisplay': '+All cameras cycle', 'optionValue': '@Index', 'type': 4, 'FPS': 5.0, 'color': 0, 'ptz': False, 'audio': True, 'width': 1920, 'height': 1080, 'isEnabled': True, 'isOnline': True, 'profile': 1, 'pause': 0, 'isPaused': False, 'isRecording': False, 'isYellow': False, 'isNoSignal': False, 'isAlerting': False, 'nAlerts': 0, 'nTriggers': 0, 'nClips': 0, 'nNoSignal': 0, 'error': '', 'isMotion': False, 'isTriggered': False}, {'optionDisplay': 'Sricam Sala', 'optionValue': 'Sala', 'active': True, 'FPS': 5.0, 'color': 8151097, 'ptz': True, 'audio': True, 'width': 1920, 'height': 1080, 'newalerts': 1771, 'lastalert': 103812800, 'alertutc': 1585402204, 'webcast': True, 'isEnabled': True, 'isOnline': True, 'hidden': False, 'tempfull': False, 'type': 4, 'profile': 1, 'lock': 0, 'pause': 0, 'isPaused': False, 'isRecording': True, 'isManRec': False, 'ManRecElapsed': 0, 'ManRecLimit': 0, 'isYellow': False, 'isMotion': False, 'isTriggered': False, 'isNoSignal': False, 'isAlerting': False, 'nAlerts': 198, 'nTriggers': 198, 'nClips': 0, 'nNoSignal': 3, 'error': ''}, {'optionDisplay': 'Sricam Cameretta', 'optionValue': 'Cameretta', 'active': True, 'FPS': 14.99, 'color': 8151097, 'ptz': True, 'audio': True, 'width': 1920, 'height': 1080, 'newalerts': 32, 'lastalert': 98354685, 'alertutc': 1585397669, 'webcast': True, 'isEnabled': True, 'isOnline': True, 'hidden': False, 'tempfull': False, 'type': 4, 'profile': 1, 'lock': 0, 'pause': 0, 'isPaused': False, 'isRecording': True, 'isManRec': False, 'ManRecElapsed': 0, 'ManRecLimit': 0, 'isYellow': False, 'isMotion': False, 'isTriggered': False, 'isNoSignal': False, 'isAlerting': False, 'nAlerts': 12, 'nTriggers': 12, 'nClips': 0, 'nNoSignal': 1, 'error': ''}, {'optionDisplay': 'Sricam Garage', 'optionValue': 'Garage', 'active': True, 'FPS': 4.9, 'color': 8151097, 'ptz': True, 'audio': True, 'width': 1280, 'height': 720, 'newalerts': 8, 'lastalert': 48077309, 'alertutc': 1585303053, 'webcast': True, 'isEnabled': True, 'isOnline': True, 'hidden': False, 'tempfull': False, 'type': 4, 'profile': 1, 'lock': 0, 'pause': 0, 'isPaused': False, 'isRecording': True, 'isManRec': False, 'ManRecElapsed': 0, 'ManRecLimit': 0, 'isYellow': False, 'isMotion': False, 'isTriggered': False, 'isNoSignal': False, 'isAlerting': False, 'nAlerts': 0, 'nTriggers': 0, 'nClips': 0, 'nNoSignal': 8, 'error': ''}]},`

` 02020-03-28 13:30:44 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=camera._sricam_cameretta, old_state=<state camera.blueiris_sricam_cameretta=idle; access_token=xxx, friendly_name=BlueIris Sricam Cameretta, stream_source=http://XXXXXX:XX/h264/Cameretta/temp.m3u8&session=XXXXX, still_image_url=http://XXXXXXX:XX/image/Cameretta?q=100&s=100&session=XXXXXX, name=Sricam Cameretta, id=Cameretta, FPS=14.89, Audio support=True, Width=1920, Height=1080, Is Online=True, Is Recording=True, Issue=False, Alerts #=12, Triggers #=12, Clips #=0, No Signal #=1, Error=, entity_picture=/api/camera_proxy/camera.blueiris_sricam_cameretta?token=XXXXXX, supported_features=2 @ 2020-03-28T13:29:46.403649+00:00>, new_state=<state camera.blueiris_sricam_cameretta=idle; access_token=XXXXXXXX, friendly_name=BlueIris Sricam Cameretta, stream_source=http://192.168.1.51:81/h264/Cameretta/temp.m3u8&session=58801cbc55011872763e2ceb43e327d0, still_image_url=http://192.168.1.51:81/image/Cameretta?q=100&s=100&session=58801cbc55011872763e2ceb43e327d0, name=Sricam Cameretta, id=Cameretta, FPS=14.99, Audio support=True, Width=1920, Height=1080, Is Online=True, Is Recording=True, Issue=False, Alerts #=12, Triggers #=12, Clips #=0, No Signal #=1, Error=, entity_picture=/api/camera_proxy/camera.blueiris_sricam_cameretta?token=75b91d4e0e25e5300a860130da27a2bb31e39e3401f958066ddf7319e7b98dc8, supported_features=2 @ 2020-03-28T13:29:46.403649+00:00>>`

`2020-03-28 13:30:44 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=camera.blueiris_sricam_sala, old_state=<state camera.blueiris_sricam_sala=idle; access_token=XXX, friendly_name=BlueIris Sricam Sala, stream_source=http://XXXX/h264/Sala/temp.m3u8&session=58801cbc55011872763e2ceb43e327d0, still_image_url=http://192.168.1.51:81/image/Sala?q=100&s=100&session=XXXXX name=Sricam Sala, id=Sala, FPS=3.4, Audio support=True, Width=1920, Height=1080, Is Online=True, Is Recording=True, Issue=True, Alerts #=198, Triggers #=198, Clips #=0, No Signal #=3, Error=, entity_picture=/api/camera_proxy/camera.blueiris_sricam_sala?token=XXXX, supported_features=2 @ 2020-03-28T13:29:46.537554+00:00>, new_state=<state camera.blueiris_sricam_sala=idle; access_token=XXXXX, friendly_name=BlueIris Sricam Sala, stream_source=http://192.168.1.51:81/h264/Sala/temp.m3u8&session=XXXXX, still_image_url=http://192.168.1.51:81/image/Sala?q=100&s=100&session=XXXX, name=Sricam Sala, id=Sala, FPS=5.0, Audio support=True, Width=1920, Height=1080, Is Online=True, Is Recording=True, Issue=False, Alerts #=198, Triggers #=198, Clips #=0, No Signal #=3, Error=, entity_picture=/api/camera_proxy/camera.blueiris_sricam_sala?token=XXXXX, supported_features=2 @ 2020-03-28T13:29:46.537554+00:00>>,`

**Comment by elad-bar** [comment]
there should be much more messages with DEBUG level, please let it run from the restart and for few minutes (~2) then post the logs,
I suggest you will set the default log level to WARNING so it will be clearer.

thanks

**Comment by detxm80** [comment]
hi elad-bar, thanks for your support. 
The only one is this:

`2020-03-29 11:06:50 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to BlueIris/+/Status`

no other logs

**Comment by elad-bar** [comment]
with the MQTT tool you are using you can publish a message, while the HA is in debug level for BlueIris custom component:
*Topic:* BlueIris/Sala/Status
*Payload:* { "type": "MOTION", "trigger": "ON" }

I would like to see the log message over there, next will be to trigger it from the BI server

**Comment by detxm80** [comment]
`2020-03-29 14:41:20 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on BlueIris/Sala/Status: b' { "type": "MOTION", "trigger": "ON" }'`

yes, if i manually pubblish topic it s working. seems to be blueiris don't pubblish topic, why?

**Comment by elad-bar** [comment]
ok, next step, debug BI server MQTT settings:
1. In the MQTT tool you are using, subscribe to topic BlueIris/#
2. In BI server go to settings
3. Tab `Digital IO and IOT`
4. Click in section `MQTT` on the `Configure...` button
5. Click on the `Test` button

Do you see any message in the MQTT tool?

![image](https://user-images.githubusercontent.com/3207137/77852115-7f92d480-71e5-11ea-929c-22bad50227a1.png)

**Comment by detxm80** [comment]
ok the mqtt server works ok, i find my error :) :) (thank you so much).

i write:
```
Topic: BlueIris/Sala/Status
Payload: { "type": "MOTION", "trigger": "ON" }
```

instead of
```
BlueIris/Sala/Status
{ "type": "MOTION", "trigger": "ON" }
```

**Comment by elad-bar** [comment]
All details of how to set it available in the README,
Enjoy it
