### ISSUE TITLE
Remove spaces from BlueIris Camera attributes

### ISSUE THREAD

**Issue by SamuelCarson** [elad-bar/ha-blueiris#43]
This is similar to "Remove spaces from Xiami switch attributes". Camera attributes with spaces cannot be used in Node-RED. Specifically Audio support:, Is Online:, and Is Recording:. 994c6e7 installed.

**Comment by elad-bar** [comment]
It supposed to be an issue in Node-RED if it cannot support something that is supported by the HA,
Is there an open issue for Node-RED?

**Comment by elad-bar** [comment]
Not sure why you think it cannot work,
In JS / Node.js Object is dictionary, the key cannot repeat itself, but can have spaces,
if you have space, you can access it by:
const property_of_some_object = some_object["key with space"];

![image](https://user-images.githubusercontent.com/3207137/77798418-e00a0080-7083-11ea-9897-f86b901318b6.png)

**Comment by SamuelCarson** [comment]
Rookie mistake. I had already discovered the JS/Node.js fix. Please close.
Sam

**Comment by SamuelCarson** [comment]
Rookie mistake. Please close.
Sam

**Comment by elad-bar** [comment]
np :)
