### ISSUE TITLE
Cannot set up Integration

### ISSUE THREAD

**Issue by flostingapplesauce** [elad-bar/ha-blueiris#44]
Entering host address and credentials results in "Invalid server details" always. No format seems acceptable. 

Running 994c6e7

**Comment by elad-bar** [comment]
can you provide the logs of the component in debug level?

thanks

**Comment by flostingapplesauce** [comment]
I do not know what "in debug level" means, but these are logs from Developer Tools. Part of it implies that it is trying to connect on port 80 instead of 81, but 81 has been entered in the Port field. I tried with :80 at the end of the URL also, but same result.

I am glad to send whatever logs are appropriate, though, just let me know how. Thanks for replying!

Log Details (WARNING)
Logger: custom_components.blueiris.password_manager
Source: custom_components/blueiris/password_manager.py:41
First occurred: 3:23:54 PM (3 occurrences)
Last logged: 4:03:03 PM

BlueIris Server password is not encrypted, please remove integration and reintegrate

Logger: custom_components.blueiris.blue_iris_api
Source: custom_components/blueiris/blue_iris_api.py:125
First occurred: 3:23:59 PM (4 occurrences)
Last logged: 4:03:08 PM

Failed to connect http://http://192.168.75.182:81/json, Error: Cannot connect to host http:80 ssl:False [Try again], Line: 110
Failed to connect http://http://192.168.75.182:81:81/json, Error: Cannot connect to host http:80 ssl:False [Try again], Line: 110
Successfully saved


Logger: custom_components.blueiris.blue_iris_api
Source: custom_components/blueiris/blue_iris_api.py:217
First occurred: 3:23:59 PM (4 occurrences)
Last logged: 4:03:08 PM

Failed to login, Error: 'NoneType' object has no attribute 'get', Line: 187
Successfully saved


Logger: custom_components.blueiris.config_flow
Source: custom_components/blueiris/config_flow.py:22
First occurred: 3:23:59 PM (4 occurrences)
Last logged: 4:03:08 PM

Failed to access BlueIris Server (http://192.168.75.182)
Failed to access BlueIris Server (http://192.168.75.182:81)
Successfully saved

**Comment by elad-bar** [comment]
It seems that the host that you've set contains http and the port,
Please remove the integration, try to add it again and before saving the config take a screenshot?

Thanks

**Comment by flostingapplesauce** [comment]
Sure - yes, I had been trying every possible combination of URL, including :81 just to see what would happen.

The logs:

Logger: custom_components.blueiris.password_manager
Source: custom_components/blueiris/password_manager.py:41
First occurred: 5:04:43 PM (1 occurrences)
Last logged: 5:04:43 PM

BlueIris Server password is not encrypted, please remove integration and reintegrate

Logger: custom_components.blueiris.config_flow
Source: custom_components/blueiris/config_flow.py:77
First occurred: 5:04:43 PM (1 occurrences)
Last logged: 5:04:43 PM

Failed to access BlueIris Server (192.168.75.182)
![BII](https://user-images.githubusercontent.com/55167013/77833801-74bd3e80-7116-11ea-9bf6-62dc3f62144a.jpg)

**Comment by flostingapplesauce** [comment]
This is the log after doing the same, with http:// in front of the host:

Logger: custom_components.blueiris.password_manager
Source: custom_components/blueiris/password_manager.py:41
First occurred: 5:04:43 PM (2 occurrences)
Last logged: 5:07:50 PM

BlueIris Server password is not encrypted, please remove integration and reintegrate
Successfully saved

Logger: custom_components.blueiris.blue_iris_api
Source: custom_components/blueiris/blue_iris_api.py:125
First occurred: 5:07:55 PM (1 occurrences)
Last logged: 5:07:55 PM

Failed to connect http://http://192.168.75.182:81/json, Error: Cannot connect to host http:80 ssl:False [Try again], Line: 110
Successfully saved

Logger: custom_components.blueiris.blue_iris_api
Source: custom_components/blueiris/blue_iris_api.py:217
First occurred: 5:07:55 PM (1 occurrences)
Last logged: 5:07:55 PM

Failed to login, Error: 'NoneType' object has no attribute 'get', Line: 187
Successfully saved

Logger: custom_components.blueiris.config_flow
Source: custom_components/blueiris/config_flow.py:22
First occurred: 5:07:55 PM (1 occurrences)
Last logged: 5:07:55 PM

Failed to access BlueIris Server (http://192.168.75.182)
Successfully saved

![BII2](https://user-images.githubusercontent.com/55167013/77833897-0c229180-7117-11ea-9dd3-7019e1f760b5.jpg)

**Comment by elad-bar** [comment]
Will check it tomorrow, when you are filling in with it should not work since the code should decide whether it's HTTP or HTTPS (based on is ssl), did you remove completely any integration of BlueIris before the first example of just IP in the host textbox?

**Comment by flostingapplesauce** [comment]
Thanks very much,

Yes, I did fully uninstall Integration With Blue Iris, restarted the server, then reinstalled. The server is certainly accessible on 81, nmap from HA shows it open, and I can pull pictures from the Blue Iris server into Lovelace using /image/cameraname/ so I do not think there is a connectivity issue,

Fresh from my last attempt:

Log Details (WARNING)
Logger: custom_components.blueiris.password_manager
Source: custom_components/blueiris/password_manager.py:41
First occurred: 5:48:07 PM (1 occurrences)
Last logged: 5:48:07 PM

BlueIris Server password is not encrypted, please remove integration and reintegrate

Log Details (WARNING)
Logger: custom_components.blueiris.config_flow
Source: custom_components/blueiris/config_flow.py:77
First occurred: 5:48:08 PM (1 occurrences)
Last logged: 5:48:08 PM

Failed to access BlueIris Server (192.168.75.182)

**Comment by elad-bar** [comment]
regarding:
> BlueIris Server password is not encrypted, please remove integration and reintegrate

This is not a real issue, fixed it in the latest version (was related to #40 ),
the second issue which you cannot access BlueIris Server, that's an issue we need to solve,
Can you please post a screenshot of the webserver security settings from BI?

**Comment by elad-bar** [comment]
Mine looks like:
![image](https://user-images.githubusercontent.com/3207137/77847246-2f574a80-71c4-11ea-8230-656de1df7c92.png)

**Comment by flostingapplesauce** [comment]
Sure, 
![biwww](https://user-images.githubusercontent.com/55167013/77849149-7ed35180-7197-11ea-85de-d9e8400e3852.jpg)

![biwww2](https://user-images.githubusercontent.com/55167013/77849153-84c93280-7197-11ea-890b-b99164428501.jpg)

Thank you again, I really want HA to play nice with B.I.

**Comment by elad-bar** [comment]
Please try to check the `Use secure session keys and login page`, remove the integration and re-add it with just IP of the machine in the host,
in addition, add new user dedicated for the component to verify that it failed to login from within the BI console

thanks

**Comment by flostingapplesauce** [comment]
THANK YOU elad-bar, that did the magic! I created a new account and enabled secure session keys on the server, then removed B.I, Integration fully. Re-installed the integration and logged on with the new user. 

Not sure which did the trick, secure session keys or the new account, but either way, I am grateful. Thanks again mate, hope that you are having a fantastic weekend!

**Comment by elad-bar** [comment]
you can check which one of them was the one that help by untick the `Use session keys...` restart the HA, my guess is the username (had few poeple that asked about issues in the past, it was the same),
If it's related to the checkbox, I will need to check it or document it.

thanks and hope you will enjoy it

**Comment by flostingapplesauce** [comment]
You are right, I unchecked Secure Session Keys and restarted HA, and everything is fine.

**Comment by elad-bar** [comment]
Great, enjoy it

**Comment by billys09** [comment]
I'm having the same issue and continually getting Invalid server details. I've followed the suggestions above to no avail
