### ISSUE TITLE
High network traffic continues after visiting and leaving live view camera

### ISSUE THREAD

**Issue by kkellner** [elad-bar/ha-blueiris#45]
When lovelace card is set to `camera view` = `live`, network traffic to hass is > 1.5Mbps.   This is expected as we are live streaming.  However when you leave the lovelace view, the high network traffic continues.   Note that `Preload stream` is not checked.   You can even logout of HA and high traffic into HA continues.

When the `camera view` is changed back to `auto`, the high network traffic continues as if there is a background thread still streaming.   If I restart hass core the network traffic returns to normal.

![image](https://user-images.githubusercontent.com/9540241/78116343-5f1f7180-73c1-11ea-81a5-3e699dd4ad43.png)

Network traffic after visiting lovelace with live stream camera, then doing a hass logout.
![image](https://user-images.githubusercontent.com/9540241/78115709-6f831c80-73c0-11ea-81d0-3979625ea668.png)

**Comment by elad-bar** [comment]
this is not related to the BI component, it's more related to HA and lovelace,
Sorry, not sure I can help, but will check it anyway during the weekend

**Comment by kkellner** [comment]
Thanks for the response!   

The traffic level returned to normal after about 5 minutes from leaving the lovelace video page.  So maybe it's just a performance thing --  keeping the stream alive to allow quick viewing (if you have viewed the live stream in the last 5 minutes).

![image](https://user-images.githubusercontent.com/9540241/78120434-2e423b00-73c7-11ea-9d2d-85d21361708f.png)

I also noticed that the lovelace live stream is about 10-15 seconds behind what is really live.  When stream is viewed from blue iris web, it's only 0.5 or 1 second behind live.   I assume this is also a artifact of the lovelace card?   Is your setup also showing live as 10 seconds behind?   Just checking if there is anything wrong with my setup.    

My goal was to show a lovelace live video view when the doorbell is pressed, but having a 10 second lag isn't so useful.

**Comment by elad-bar** [comment]
https://www.home-assistant.io/lovelace/picture-elements/

Under IMAGE ELEMENT:
camera_view
(string)(Optional)
“live” will show the live view if stream is enabled.

Default value:
auto

**Comment by elad-bar** [comment]
@kkellner, is it still an issue?

thanks

**Comment by kkellner** [comment]
Something continues to steam data 5 minutes after you leave HA.  But I'll assume its by design.   Closing Issue.
