### ISSUE TITLE
Binary motion sensors status not updated

### ISSUE THREAD

**Issue by thecode** [elad-bar/ha-blueiris#48]
Since commit e41138db07b165e1c02775714d699d887bd876bf the status of binary motion sensors are not updated.
I've verified that the Blue Iris server is sending the correct MQTT status updates and with commit bf1c2801205d80daf3bf33c383ed0b7e749d469b they are working correctly.
Thanks for the effort and fast response.

**Comment by axan2149** [comment]
yup same, motion and audio detection broken after last update.

**Comment by elad-bar** [comment]
Can you check if in the latest version it was solved?
For me it works

**Comment by axan2149** [comment]
upgraded to latest version, works great now. Thanks

**Comment by thecode** [comment]
Everythings works ok. Big thanks!
