### ISSUE TITLE
At each reboot, the entities are incremented

### ISSUE THREAD

**Issue by Shyrka973** [elad-bar/ha-blueiris#50]
Hi,

Since a few days, when I reboot HA, the entities are incremented.
If I rename them manually, it's ok until the next reboot.

Thanks.

Installed version: e41138d

**Comment by elad-bar** [comment]
Please try updating to the latest version, if it still doing the same, remove the integration and readd it, it happened for me too,
With the latest version it was fixed

**Comment by Shyrka973** [comment]
I did the update.
I manually renamed the entities correctly.
At the reboot, they were not renamed. 
It's ok for me.

Thanks !

Installed version: d997e89
