### ISSUE TITLE
Unable to set up dependencies of blueiris. Setup failed for dependencies: mqtt

### ISSUE THREAD

**Issue by drittzz** [elad-bar/ha-blueiris#56]
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:129
First occurred: 1:33:40 PM (1 occurrences)
Last logged: 1:33:40 PM

Unable to set up dependencies of blueiris. Setup failed for dependencies: mqtt

Integration with Blue Iris NVR
Integration with Blue Iris Video Security Software
Authors:
elad-bar
GitHub stars: 38
Last updated: 3 hours ago
Installed: fe8b9b9
Available: fe8b9b9

**Comment by robertw** [comment]
yes that was it .....
