### ISSUE TITLE
since update will not load removed reinstalled and config not coming up

### ISSUE THREAD

**Issue by robertw** [elad-bar/ha-blueiris#58]
Home Assistant 0.108.8
Integrations just looping after select blue iris loops back to select integrations config screen not coming up 
then :
uninstalled from hacs
then rebooted
then reinstalled and same thing just looping

**Comment by elad-bar** [comment]
please post log

**Comment by robertw** [comment]
what ever you did on the new update it loaded and config came up no icon in integration but we looking ok so far thanks

**Comment by elad-bar** [comment]
So you probably don't use mqtt and it might be related to #56
