### ISSUE TITLE
Failed to call service blueiris/generate_advanced_configurations

### ISSUE THREAD

**Issue by philgree** [elad-bar/ha-blueiris#60]
Thanks for creating this, it makes tie in to Blue Iris much easier :)

It's mostly working for me with entities being created in HA including images being accessible through the camera entities. I am however receiving a "Failed to call service blueiris/generate_advanced_configurations. 'BlueIrisApi' object has no attribute 'username'" error when I attempt to call the "blueiris.generate_advanced_configurations" service.

Also (minor point) the "Example of UI layout" and "Example of configuration output" links at "https://github.com/elad-bar/ha-blueiris" both result in 404 errors.

Cheers

Phil

**Comment by elad-bar** [comment]
please check

**Comment by philgree** [comment]
Thanks for the prompt response. I can see you've made some adjustments (thank you), and my experience has changed, but I'm still unable to use casting as described in the repository documentation.

#Additional detail:


##About my system:

I'm running HassOS within Proxmox on an Intel NUC. The "Integration with Blue Iris NVR" integration has been included via HACs. Proxmox, HassOS, Blue Iris, HAC and the Blue Iris integration were all at the most recent versions as or yesterday when I logged my issue report.


##Steps taken in retesting today: 

1. I've applied the upgraded from Home Assistant Core Assistant Core to 0.108.9 released overnight (previously 0.108.8)
2. I've applied the latest release of the Blue Iris integration (now 1a1b95d)
3. I've restarted Home Assistant to apply these two changes.

##Results of testing:

1. The two links in the integration repository documentation to the UI layout and configuration output examples is now working correctly - thank you.

2. The 'blueiris.generate_advanced_configurations' service which previous reported an api error no longer exists.

3. I note there is an option "generate configuration files" within the integration options which I didn't previously see. From the current docs I think you've added this to replace the 'blueiris.generate_advanced' service. I've selected this option and pressed submit. No errors were reported so I imagine this has completed successfully (?)

I checked for, but do not have, the 'input_select.camera_dropdown', 'input_select.camera_dropdown' and 'script.execute_cast_dropdown' entities referred under 'casting' in the documentation.
