### ISSUE TITLE
Entities referred to in 'casting' section of docs do not appear

### ISSUE THREAD

**Issue by philgree** [elad-bar/ha-blueiris#61]
please check

_Originally posted by @elad-bar in https://github.com/elad-bar/ha-blueiris/issues/60#issuecomment-619344986_

**Comment by philgree** [comment]
Thanks for the prompt response. I can see you've made some adjustments (thank you), and my experience has changed, but I'm still unable to use casting as described in the repository documentation.

#Additional detail:

##About my system:

I'm running HassOS within Proxmox on an Intel NUC. The "Integration with Blue Iris NVR" integration has been included via HACs. Proxmox, HassOS, Blue Iris, HAC and the Blue Iris integration were all at the most recent versions as or yesterday when I logged my issue report.

##Steps taken in retesting today:

I've applied the upgraded from Home Assistant Core Assistant Core to 0.108.9 released overnight (previously 0.108.8)
I've applied the latest release of the Blue Iris integration (now 1a1b95d)
I've restarted Home Assistant to apply these two changes.
##Results of testing:

The two links in the integration repository documentation to the UI layout and configuration output examples is now working correctly - thank you.

The 'blueiris.generate_advanced_configurations' service which previous reported an api error no longer exists.

I note there is an option "generate configuration files" within the integration options which I didn't previously see. From the current docs I think you've added this to replace the 'blueiris.generate_advanced' service. I've selected this option and pressed submit. No errors were reported so I imagine this has completed successfully (?)

I checked for, but do not have, the 'input_select.camera_dropdown', 'input_select.camera_dropdown' and 'script.execute_cast_dropdown' entities referred under 'casting' in the documentation.

**Comment by elad-bar** [comment]
it doesn't create the component, it just preparing the components in CONFIG folder, you can take it from there and add it to HA

**Comment by philgree** [comment]
Ah, sorry, I misunderstood. In that case, I can confirm that those files are indeed sitting in the config folder waiting for me to integrate them into HA. 

Thanks again, your integration has taken my Blue Iris to HA integration further than I had it previously. I really appreciate your efforts :)

**Comment by elad-bar** [comment]
glad it works for you good,
Will work on creating the input_select auto generated without need to run the service, will update once it's ready
