### ISSUE TITLE
Integration re-adds all sensors

### ISSUE THREAD

**Issue by iptvcld** [elad-bar/ha-blueiris#62]
If i disable all the motions sensors from the integration and then go back and enable just 1 motion sensor - in about 30 seconds, the page refreshes and it re-adds all the sensors.  Almost like a re-install.

Also when I do have the 1 motion; sometimes it triggers OK and sometimes it does not via BI5 MQTT - using the same payload in your example.

**Comment by iptvcld** [comment]
once you disable items the motion sensors still listing to MQTT

**Comment by iptvcld** [comment]
Thanks for looking into this. Piror to updating to the new release. I had all sensors disabled execpt for cameras. I performed the update and restarted HA and enabled 1 motion, saved. Then enabled 1 more sensor. And when I exited the integration page and went back in. All my sensors Re enabled. It's so much work to disable them all.

**Comment by elad-bar** [comment]
why do you disable them?

**Comment by iptvcld** [comment]
I have 9 cams and I just need the cams because they show good attributes and then I just 1 motion which I use an automation for

**Comment by iptvcld** [comment]
Please let me know if a change can be made and i will test it out right away.. You have a nice integration here!

**Comment by elad-bar** [comment]
I'm thinking of how to implement the options to let anyone control just what they want, maybe display per camera in options multi select drop down to choose per camera to enable / disable: camera, motion sensor, audio sensor, watchdog sensor

WDYT?

**Comment by iptvcld** [comment]
Oh that would be amazing! And by default perhaps everything set to cameras enabled only. And the users can then choose to enable which ever sensor they would like under each cam

**Comment by iptvcld** [comment]
Thanks; i see that there was an update today - i updated and then removed my integration to start from the start.  When i go to add the integration, it says added but nothing shows up in the integration list now. I have even rebooted HA (This integration has no devices.)

**Comment by elad-bar** [comment]
Released new version, can you please check if it works for you now?
