### ISSUE TITLE
Latest update broke entities

### ISSUE THREAD

**Issue by iptvcld** [elad-bar/ha-blueiris#64]
All our sensors, Cams now have the BI server IP in the name for example (camera.192_168_2_9_backyard) and now we will need to update Lovelace to display these entities as there was a name change.

Before: camera.blueiris_backyard
Now: camera.192_168_2_9_backyard

**Comment by elad-bar** [comment]
Issue caused by moving the name of the integration to the title, until now the title was the url of the BlueIris server, from that version name is being taken from the BlueIris server name.

There are 2 ways to fix the title:
1. Remove and re-add the integration
2. Edit in ./storage/core.config_entries the integration’s title to the title you would like it to be (below is an Exmaple of BlueIris):

```json
{
  "connection_class": "local_poll",
  "data": {
    "host": "hostname",
    "password": "encrypted_password",
    "port": "port",
    "ssl": false,
    "username": "username"
  },
  "domain": "blueiris",
  "entry_id": "d5a28bf9e180458db8cab34866eb31a8",
  "options": {},
  "source": "user",
  "system_options": {
    "disable_new_entities": false
  },
  "title": "BlueIris",
  "unique_id": null,
  "version": 1
}
```

after updating the file, restart the HA

**Comment by iptvcld** [comment]
Thanks for the explanation, I assume this is for sure a breaking change. As I have other sensors that read the values from the cam and since the cam name change, I will now need to also update those names. Hope this is a perm name change so that we don't have to re do them again. Thanks

**Comment by elad-bar** [comment]
Sorry for that breaking change but it was a must to mange the integration correctly

**Comment by iptvcld** [comment]
And is it correct to be showing the BI IP in the name? As my BI server name is BlueirisNVR but I don't see that coming through in the sensor name.

**Comment by iptvcld** [comment]
Great work for keeping this up to date though!

**Comment by elad-bar** [comment]
The previous title taken from the hostname or ip, now it will get updated by the name of server defined in BI app

**Comment by iptvcld** [comment]
I have the latest update and rebooted a few times but the cam name is camera.192_168_2_9_backyard

I see that the integration title pulled the correct name under the integration section in HA. But the cam and sensors have the IP in the name. Is this correct? Should this also pull the BI server name?

**Comment by iptvcld** [comment]
Fully removed integration and re-installed. Now cam entity shows back to the way it was before
camera.blueiris_backyard - this was odd as when I updated today it was showing camera.192_168_2_9_backyard. My BI server name is BlueIrisNVR

**Comment by sankeerthb** [comment]
I have fully removed the integration, uninstalled the plugin as well, and
redid all. Also, renamed the entities back to original.
Back to normal again.

**Comment by elad-bar** [comment]
Can we close that issue?
I will document the issue resulted from that version and possible ways to solve it

Thanks

**Comment by iptvcld** [comment]
Yup. All good! Thanks

**Comment by Shyrka973** [comment]
Hi,

I deleted the entities containing BlueIris but I still have: still the old BlueIris Server (circled in red).
The voucher is surrounded in green.
I don't know how to delete it. So I have to fully remove the integration ?

![image](https://user-images.githubusercontent.com/5006726/80868832-467dd200-8c73-11ea-9336-3594329ef21c.png)

Thanks.
