### ISSUE TITLE
The description of the fields is missing

### ISSUE THREAD

**Issue by Shyrka973** [elad-bar/ha-blueiris#65]
Hi,

With last integration (d2ba3fc), i get this:
![image](https://user-images.githubusercontent.com/5006726/80868475-3c5ad400-8c71-11ea-90a9-433e06e2ea40.png)

I use French.

Thanks.

**Comment by elad-bar** [comment]
what HA version are you using?

**Comment by Shyrka973** [comment]
0.108.9

**Comment by elad-bar** [comment]
translation's directory changed in v0.109, can you please upgrade to HA 0.109 and recheck?

**Comment by Shyrka973** [comment]
I'm waiting for 0.109.3 or 0.109.4. A more stable version.

Thanks.

**Comment by elad-bar** [comment]
Next time I will set minimum version of HA as requirement 

Thanks

**Comment by Shyrka973** [comment]
Hi,

With 0.109.3, the descriptions are there.

Thanks.
