### ISSUE TITLE
Unable to add integration without user id and password

### ISSUE THREAD

**Issue by Shyrka973** [elad-bar/ha-blueiris#66]
Hi,

I deleted the integration. I can no longer reinstall it.
Integration absolutely wants a user id and password.

My BlueIris installation does not use a password.

Thanks.

**Comment by Shyrka973** [comment]
I successfully integrated without the user id and password. But I put the IP address and the identities only use the IP address.
Is this normal?
![image](https://user-images.githubusercontent.com/5006726/80871120-3240d180-8c81-11ea-94f1-b0150f9ea250.png)

**Comment by elad-bar** [comment]
Not sure I understand the question,  can you please explain the steps and the issue?

Thanks

**Comment by Shyrka973** [comment]
HI,

Everything works as it should. I close this ticket.

Thanks.
