### ISSUE TITLE
Not able to display to firestick tv

### ISSUE THREAD

**Issue by iptvcld** [elad-bar/ha-blueiris#67]
Is this possible? Thank you

**Comment by elad-bar** [comment]
not sure I understand the issue and what is the expected result,
can you provide more details?

**Comment by iptvcld** [comment]
Wondering if it is possible to display the camara.front let's say to a TV device?

**Comment by elad-bar** [comment]
for me it works, there is an option to generate configuration with script (mroe details in README),
Once created and added to HA, you can use the script to cast from one of the `camera` to one of the `media_player`.

I think it's a must to have HA with SSL to support that capability.

**Comment by iptvcld** [comment]
I see in your example. media_content_id is the url can't we just use the camera entity

**Comment by elad-bar** [comment]
can you post and example how you vision it?

**Comment by iptvcld** [comment]
I would like so on motion, display a popup on the media player tv with the camera live stream

**Comment by elad-bar** [comment]
In that case, you need to use the Integration -> Options to generate the configuration, add the components it generated to the config folder of HA and simply write automation to do that,
you can also use NodeRED to implement such flow
Listen to binary sensor change -> Call Service of cast to specific media player from the corresponding camera
