### ISSUE TITLE
hostname not accepted, only IP number

### ISSUE THREAD

**Issue by Dinth** [elad-bar/ha-blueiris#68]
Hi. Im struggling with hostnames not being accepted as BlueIris server number.
Everything works fine when i put BlueIris IP number in the settings, but when i change it to hostname, im getting an "Invalid server details" error.
The hostname should resolve to IP number, the DNS server resolves it, DNS address is correct in DHCP and firewall automatically redirects all other, outgoing DNS queries to the local DNS server.
I can resolve the hostname from within HassOS too.

**Comment by elad-bar** [comment]
can you please post the configuration screenshot before saving and logs after saving (with the error)?

thanks

**Comment by Dinth** [comment]
Sorry, i have managed to resolve this.
1. Done "ha dns --server <dns>" command, as the server was only showing up in locals not servers of "ha dns info".
2. Added domain name to the hostname.
