### ISSUE TITLE
Profile Switch

### ISSUE THREAD

**Issue by iptvcld** [elad-bar/ha-blueiris#70]
When using the profile switch to change the BI profile, when you turn the switch off - does it go back to the switch you had before turning on the switch?

Lets say you have a day and night profile in BI and then you turn on the switch for lets say NoAlerts Profile.  If you turn it off at night, will it know to use your set schedule?

**Comment by elad-bar** [comment]
I changed it to work according to the switches in HA,
Meaning, once you've set the desired switch to on - it will automatically turn it on and lock it
once you've truned it off, it will go to the default (1) and lock it

**Comment by iptvcld** [comment]
In HA when I change a profile it will remain there until the next scheduled
profile change time. That is better Imo. That way if you forget to change
it then it will follow the schedule. Thanks

**Comment by elad-bar** [comment]
Maybe I should add an option to configure in options whether it should be controlled by HA or BI.

For some users like you, prefer the automation to happen in BI,
For users like me, prefer to have the control in one place which is HA (I'm using NodeRED to control scenes which one of the actions is to set the profile)

what do you think?

**Comment by iceman73** [comment]
I like this controlled by the user idea, as I also want the BI automation to kick back in after a specified period of time
