### ISSUE TITLE
Getting binary_sensor into home assistant

### ISSUE THREAD

**Issue by welbo97** [elad-bar/ha-blueiris#71]
I don't see how the binary sensors for motion and connectivity are added to Home Assistant. I have set it up so that I see the sensors activating in MQTT with an explorer program. I have MQTT integration added and working with discovery for some other (tasmota) devices. But they write to the topic 'homeassistant/binary_sensor/...' with the discovery information. I do not see Blue Iris doing that. 

Do I have to add each of the sensors manually through the configuration.yaml files? 

I also enabled "Write configuration files" but have not been able to find any written config files. What directory will they be written to? I looked in /custom_components/blueiris/ and it's sub directories.

**Comment by elad-bar** [comment]
Component is working with MQTT not with discovery which explains why it's not publishing the topic with homeassistant/...

Just to be sure, you have entered valid credentials for BI in the setup of component and MQTT is setup correctly?
In case you did, did you set the MQTT correctly in BI server (According to the README)?
Did you choose any of the camera for specific sensor in integration's options?

Generate config files can be found in .storage directory

**Comment by welbo97** [comment]
I fear I may not have something set up correctly. Here are the details of my setup:

I have a mosquitto mqtt broker running in an lxc for my home automation. I use MQTT explorer application to view/modify the topics. 

I set up BI to use this MQTT broker with credentials in the settings/info page of BI. Then I set up each of my cameras with alert and watchdog topics to publish to. I am able to see the app and motion topics appear via MQTT explorer so I believe it is set up properly in BI (just as the readme explained).

I see 8 devices in the HA-BlueIris integration on the HA integrations page. Each device automatically created several entities, camera, motion, audio, connectivity. The camera feeds work properly in the HA UI. But none of the other binary sensors or sensors appear to work. They all show 'unavailable'. 

I have added the MQTT integration into HA and enabled 'Discovery' and told it to 'Enable new entities'. Do I need to do anything else to get the motion and connectivity sensors to show available in HA?

In the HA "Integrations" page, I clicked on 'Options' on the Blue Iris NVR integration, clicked 'Reset to default configuration' then 'submit'. Then I clicked 'Options' again, clicked 'Generate configuration files' and 'submit'. I searched in the /config/.storage directory and see no files related to Blue Iris. I searched in the /config/custom_components/blueiris and see no generated config files. There is a 'services.yaml' but it is 0KB. 

The only recent log entries regarding blueiris say 'Retrieving camera list' and 'Retrieving status' repetitively. I have 'Info' logging enabled. 

I have removed and reinstalled the HA-Blueiris integrations a few times. What else can I do to try and make it work?

**Comment by hobybrenner** [comment]
Same issue here I am trying to figure out what MQTT topic that the component is expecting.

**Comment by welbo97** [comment]
I revealed a problem with my configuration. My cameras are triggered externally via deepstack AI tool and therefore the topic that was being published was /BlueIris/EXTERN/status because of the variable ```&TYPE``` in the alert topic. I replaced that with a hard coded /BlueIris/MOTION/status however the HA MQTT integration still did not associate it with the motion sensors HA-Blueiris created. Then I deleted the old MQTT topics using MQTT explorer that existed in my broker. After that, the motion sensor began working. I do not think I have any use for the other types of trigger from Blue Iris so this solution works for me. Possibly you should consider allow other triggers to activate the motion binary_sensors within HA.

**Comment by hobybrenner** [comment]
welbo97 thanks for the reply!  I think that is my problem as well as I had setup everything by hand previously and thought I had nuked everything to use the addin.  For now I reverted, but I will look to this when I give it a try again!  Thanks!

**Comment by welbo97** [comment]
I have added new cameras and set the MQTT topic for the motion sensors to ```/BlueIris/MOTION/status``` on each of them. They have appeared as binary sensors properly in Home Assistant. Thank you for your response @elad-bar . I will mark the issue closed.
