### ISSUE TITLE
HOme Assistant 0.112

### ISSUE THREAD

**Issue by bartekd123** [elad-bar/ha-blueiris#73]
Since I updated to home assistant 0.112 I don't see my cameras anymore. They show as unavailable. Looking through the home assistant log, I don't see any errors. Is it compatible?
I just updated to 0.112.1 and see the same issue.

**Comment by elad-bar** [comment]
are you using stream component or default configuration of HA?
can you attach screenshot of how it looks?

thanks

**Comment by bartekd123** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/16650162/86474334-9b3fd680-bd10-11ea-817f-ca96e6101efd.png">

**Comment by bartekd123** [comment]
<img width="1266" alt="Screen Shot 2020-07-03 at 9 35 50 AM" src="https://user-images.githubusercontent.com/16650162/86474393-b874a500-bd10-11ea-841c-59a53b9391fa.png">

**Comment by bartekd123** [comment]
There is some screenshots. I don't think I am using the stream component (assuming you mean another addon?)

**Comment by elad-bar** [comment]
you are using stream component, it will not work.

can you publish the log:
change log level to debug (from integration -> BI -> options) and restart the HA

thanks

**Comment by elad-bar** [comment]
> I don't think I am using the stream component

the `preload stream` in screenshot is an indication that HA is using the stream component

**Comment by bartekd123** [comment]
2020-07-03 09:41:53 ERROR (MainThread) [custom_components.blueiris] Failed to load BlueIris, error: Unable to find service logger/set_level, line: 27

Thats all I see in my log file after setting it to debug.

**Comment by bartekd123** [comment]
After setting it to debug, and restart HA, I can't load the options in the home assistant integrations. Is there a manual way to set it?

**Comment by elad-bar** [comment]
is there an error in logs after restart?
did you update the component over the last few days?

**Comment by bartekd123** [comment]
I grep'ed my homeassistant.log for blue and only see the error I mentioned. Looks like it didn't like me setting it to debug.

I keep it pretty up to date using HACS. So if there was an update recently, I would have updated it. I don't remember specifically.

**Comment by bartekd123** [comment]
I deleted the integration, re-added it and re-configured and it looks like it works now. Thanks for your help, and quick replies!

Side note, what do you recommend using instead of stream? I find it works, but sometimes you need to click it and close it a couple times.

**Comment by elad-bar** [comment]
stream has huge delay (up to 10 seconds), by disabling the stream component, it reduced to just 2-3 seconds delay.
In addition, stream causes the server to work much harder (I have 16 camera) and when I switched the streaming from BI to HW Acceleration (NVidia), it's not working well...

**Comment by bartekd123** [comment]
Thanks for your help. I didn't even know I had stream enabled, and thought it was there by default. 

This issue can be closed. After removing and re-adding the integration, everything is back to normal.
