### ISSUE TITLE
Support for BI virtual path in Web Server

### ISSUE THREAD

**Issue by jasonatepaint** [elad-bar/ha-blueiris#78]
### Issue
The integration doesn't support the virtual property in BI's Web Server, preventing a reverse-proxy setup where the virtual path is required.

### Proposal
Instead of asking for Host/Port, a complete URL may allow for the flexibility needed.  This way you're checking for a complete/valid URI and you'll know if it's SSL by the transport protocol (HTTP/S).

example:  ` http://x.x.x.x/virtual_path`

Default ports would be used (80/443) unless also included in the URI.

---
Thanks and great work!

**Comment by elad-bar** [comment]
I can add virtual path parameter to the editor, changing the parameters into 1 would be much more complex since it's breaking change and I will need to handle it 

will it work for you?

thanks

**Comment by elad-bar** [comment]
@jasonatepaint any updates?
