### ISSUE TITLE
HA-Blueiris stopped working and "User input malformed" error

### ISSUE THREAD

**Issue by Dinth** [elad-bar/ha-blueiris#79]
Hey. I had BlueIris component set up and working until few days ago it suddenly stopped working. I dont recall changing any configuration, definetely not in the component itself when it stopped working.
```
Request #1 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'status', 'session': '44b0304d3b9a5dd765a0416a6d9d4159'}, Response: {'result': 'fail', 'session': '44b0304d3b9a5dd765a0416a6d9d4159'}
Request #0 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'status', 'session': '029d1a7d690c5dab634f318443093f89'}, Response: {'result': 'fail', 'session': '029d1a7d690c5dab634f318443093f89'}
Request #1 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'status', 'session': '029d1a7d690c5dab634f318443093f89'}, Response: {'result': 'fail', 'session': '029d1a7d690c5dab634f318443093f89'}
Request #0 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'status', 'session': '02965ed76cb400db32e3431c7de93e38'}, Response: {'result': 'fail', 'session': '02965ed76cb400db32e3431c7de93e38'}
Request #1 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'status', 'session': '02965ed76cb400db32e3431c7de93e38'}, Response: {'result': 'fail', 'session': '02965ed76cb400db32e3431c7de93e38'}
Request #1 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'camlist', 'session': '13643a3d387661dd4377568049b2456e'}, Response: {'result': 'fail', 'session': '13643a3d387661dd4377568049b2456e'}
Request #0 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'camlist', 'session': '682f0c1c473b111c05283b094b254397'}, Response: {'result': 'fail', 'session': '682f0c1c473b111c05283b094b254397'}
Request #1 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'camlist', 'session': '682f0c1c473b111c05283b094b254397'}, Response: {'result': 'fail', 'session': '682f0c1c473b111c05283b094b254397'}
Request #0 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'camlist', 'session': '3cfb5dfc55ff405b46d81f914c9841c1'}, Response: {'result': 'fail', 'session': '3cfb5dfc55ff405b46d81f914c9841c1'}
Request #1 to BlueIris (http://10.10.1.14:81) failed, Data: {'cmd': 'camlist', 'session': '3cfb5dfc55ff405b46d81f914c9841c1'}, Response: {'result': 'fail', 'session': '3cfb5dfc55ff405b46d81f914c9841c1'}
```
After that i have tried checking the component configuration, but noticed really weird behaviour. None of the dropdown menus can be opened (the ones where i can chose sensors), but most importantly, whenever i want to save changes im getting "User input malformed" error.

![Screenshot 2020-07-30 at 22 11 35](https://user-images.githubusercontent.com/313674/88975702-94c26180-d2b2-11ea-8ffd-8857f069ab6b.png)
![Screenshot 2020-07-30 at 22 11 27](https://user-images.githubusercontent.com/313674/88975713-9a1fac00-d2b2-11ea-81ae-b3e566109d9b.png)

**Comment by welbo97** [comment]
Same problem here. I removed the integration and when I tried to reinstall fro HACS, it doesn't even show up in the repository list anymore. This started after a full server reboot, which included the BlueIris 5 Win10 vm.

**Comment by elad-bar** [comment]
please remove the integration and make sure you don't have .storage/.blueiris file,
afterwards, please restart the HA and try to add it once the HA fully started up

thanks

**Comment by welbo97** [comment]
Removing the integration, removing the .storage/.blueiris file, restarting and re-adding the integration solved the problem for me.

**Comment by FuzzyMistborn** [comment]
Running into this now.  Everything was working great.  But then the cameras froze/wouldn't stream, so I tried to remove/readd and when I did I ran into the user input malformed error.  Tried clearing out the .blueiris file and restarting several times, no luck.

**Comment by sdwilsh** [comment]
I'm also hitting this on a clean install of Home Assistant (and consequentially this integration).

**Comment by elad-bar** [comment]
It seems that the issue consisted with 3 different scenarios, first reported about lack of access to the server by @Dinth, was the issue fixed or still need me to investigate? 
@welbo97 @FuzzyMistborn @sdwilsh are you still experiencing the same issue reported by @Dinth? If not, please open a separated issue

Thanks

**Comment by Dinth** [comment]
Hi @elad-bar. I have removed the integration and addon (in HACS), manually removed .blueiris file, reinstalled the integration and tried to set it up, but im still getting User input malformed

**Comment by elad-bar** [comment]
Please post the log after loading the HA with Debug log level for that component,
Based on that information I'll try to reproduce it

Thanks

**Comment by Dinth** [comment]
Hi again. Actually, i have just tried to add it again, clicked "Reinstall" in HACS, double checked if .blueiris file is still absent, added integration and it worked. Im not sure why it was not working a week ago, but it definetely works now. 
Thank you!

**Comment by Dinth** [comment]
@welbo97 @FuzzyMistborn @sdwilsh can you please confirm if it works for you/try again if it doesnt?

**Comment by FuzzyMistborn** [comment]
Yes I got it working after trying again a bit later.

**Comment by dickeos** [comment]
Hello, I have just installed the BlueIris component on a clean HA install, and get this error message when logging in. I wnat to remove and try a reinstall as stated in this post but for the life of me I don't know where  .storage/.blueiris file is. I am running on a x86 NUC, I think its running under Busybox

**Comment by kramttocs** [comment]
@dickeos 
Take a look at this thread and see if it helps.
It lists a few ways to see the hidden folders
https://community.home-assistant.io/t/access-storage-folder/190186/18

**Comment by dickeos** [comment]
Thanks for responding. I have checked and the file does not exist, I have re installed but I still get "User input malformed: expected str for dictionary value @ data['port']"

I followed the install guide word for word.

Is there a specific version of BlueIris it needs to work with? I am using V5.5.1.12

**Comment by dickeos** [comment]
Figured it.... BI cant be on port 80. Used port 81 and all is well.
