### ISSUE TITLE
Custom entity renames revert on reboot

### ISSUE THREAD

**Issue by FuzzyMistborn** [elad-bar/ha-blueiris#87]
May be related to #85, not sure, but I have noticed after updating to v1.0 of the component that when I rebooted HASS, the component renames all the entities back to the default names.  Which is a problem for me because I rename the motion and connectivity sensors to `binary_sensor.blueiris_connectivity_XXXXXX` and `binary_sensor.blueiris_motion_XXXX` to take advantage of using substrings in NodeRed, instead of having to create separate nodes for each sensor.

Happens to me on every reboot.

**Comment by MarkHofmann11** [comment]
Yes, seeing the same thing over here.

**Comment by elad-bar** [comment]
dup #85
