### ISSUE TITLE
Watch Item: HA Issue "Stream Proxy Performance Poor with Blue Iris #23549"

### ISSUE THREAD

**Issue by darkgrue** [elad-bar/ha-blueiris#9]
Opened HA Issue ["Stream Proxy Performance Poor with Blue Iris #23549"](https://github.com/home-assistant/home-assistant/issues/23549) to see if it can be possible to bypass the Stream proxy and go straight to the Blue Iris HLS stream. This should, in theory, improve streaming performance dramatically.

**Comment by stratplayer** [comment]
I can barely get any stream to work either

**Comment by elad-bar** [comment]
If you are using the stream component it will not work if you have more than 2-3 camera, the BI will get to 100% of cpu,
That is being caused by multiple WS that samples the server in parallel,  nothing i can assist with,
Unless you have a solution for that

**Comment by stratplayer** [comment]
I am just using what is setup by default. I have 7 cameras in BI. When I select to view the stream from one of them my CPU usage doesn’t change at all, sits at 22%. I just have the window pop up on HA with the spinning logo and Pre-Load stream option.

**Comment by elad-bar** [comment]
In case you have the preload check box it means you are working with stream, disable ot and it will work, component currently doesn't work with stream

**Comment by stratplayer** [comment]
Sorry, I am not very good with the stream/camera bits in HA. The option for Pre-Load stream is not enabled on my setup. Is there something else I need to change?

**Comment by elad-bar** [comment]
Can you please post a screenshot how it looks?
In addition, can you upload log file related to component?

Thanks
