### ISSUE TITLE
Issue on initial install

### ISSUE THREAD

**Issue by joshrow85** [elad-bar/ha-blueiris#98]
When I attempt to add this integration it acts like it is installing then just goes back to the list of integrations and I get this error in the logs.  Any idea what I'm doing wrong?

Logger: homeassistant.config_entries
Source: config_entries.py:546
First occurred: 7:30:07 PM (2 occurrences)
Last logged: 7:30:48 PM

Error occurred loading configuration flow for integration blueiris: cannot import name 'CONF_PAYLOAD_AVAILABLE' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)

**Comment by Mdleal** [comment]
I received this error after updating to the latest beta of HA 2021-02. I reverted back to 2021-01

**Comment by elad-bar** [comment]
Thanks for the heads-up, will check
